### ISSUE TITLE
The sidebar in the administration dashboard doesn't resize if player is opened 

### ISSUE THREAD

**Issue by KristupasSavickas** [jellyfin/jellyfin-web#1090] opened 2020-04-15 10:15 UTC
Opening the player and navigating to the administration dashboard might lead to invisible sidebar entries, as the sidebar doesn't respond to the player state (see screenshot).

**Screenshots**

![Screenshot_20200415_125041](https://user-images.githubusercontent.com/1362643/79324130-c982f680-7f17-11ea-9f2a-2b594d99923c.png)

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Fifrefox 75.0
 - Jellyfin Version: 10.5.4

**Comment by rexbron** [comment] 2020-04-23 15:53
@MrTimscampi I fixed (perhaps poorly) the screenshotted issue above when PR 1034 was merged.  
That change from padding-bottom to margin-bottom slipped in. 

That said, I think there is a larger underlying issue with how the playbar is implimented and just patching it every time there is a UI overlap is a bandaid.

**Comment by rexbron** [comment] 2020-04-23 15:56
I'd also argue that is bug is a dupe of #1035 :)

**Comment by MrTimscampi** [comment] 2020-04-23 17:13
> That said, I think there is a larger underlying issue with how the playbar is implemented and just patching it every time there is a UI overlap is a bandaid.

Agreed! I tried to reorganize the DOM earlier today by changing this:

```html
<body>
    <div class="backdropContainer"></div>
    <div class="backgroundContainer"></div>
    <div class="mainDrawer hide">
        <div class="mainDrawer-scrollContainer scrollContainer focuscontainer-y"></div>
    </div>
    <div class="skinHeader focuscontainer-x"></div>
    <div class="mainAnimatedPages skinBody"></div>
    <div class="mainDrawerHandle"></div>

    <!-- inject:js -->
    <!-- endinject -->
</body>
```

To this in index.html:

```html
<body>
        <div class="app">
        <div class="backdropContainer"></div>
        <div class="backgroundContainer"></div>
        <div class="mainDrawer hide">
            <div class="mainDrawer-scrollContainer scrollContainer focuscontainer-y"></div>
        </div>
        <div class="skinHeader focuscontainer-x"></div>
        <div class="mainAnimatedPages skinBody"></div>
        <div class="mainDrawerHandle"></div>
    </div>

    <!-- inject:js -->
    <!-- endinject -->
</body>
```

And adjusting the code for appending the appfooter div to the page, so that it sits right after app instead of at the tail end of `<body>`.

The idea was to have one div containing the entire app, that can be shrunk upwards when showing the player. However, after about 30min of fiddling with CSS to get it working, I gave up :p

> I'd also argue that is bug is a dupe of #1035 :)

I totally agree this can be closed as a duplicate. I'm (slowly) making my way through the 150+ issues to tag and sort stuff and hadn't reached that one yet.

**Closed by MrTimscampi** 2020-04-23 17:13 UTC
Labels: bug
