### ISSUE TITLE
Adding server, after one typo, all further corrections fail

### ISSUE THREAD

**Issue by wassname** [jellyfin/jellyfin-web#374] opened 2019-06-27 06:23 UTC
I just noticed a little bug. When adding a new server, if you make a typo the first time, it fails to connect (e.g. https://jelyyfin.example.com:443). If you stay in the same screen, fix the typo, then try again (https://jellyfin.example.com:443), it fails to connect. 

However, if you exit to the "choose server" window and start again, the same address (https://jellyfin.example.com:443) will work.

It seems that after one failure, it will not try again. This is misleading because I thought the app was not working, or my server was not working. This is a minor bug, but it may prevent a user from trying the app.

Observed in app version 0.9.0 from the google play store, and 10.3.5-1 server on ubuntu 18.04.

Thanks for all the great work on jellyfin :) Everything works surprisingly well for a project this young.

**Comment by anthonylavado** [comment] 2019-07-02 04:50
This sounds like an -Android, right @dkanada?

**Comment by MrTimscampi** [comment] 2020-06-05 12:30
Closing this as I can't reproduce it on the current Android app nor on web.

**Closed by MrTimscampi** 2020-06-05 12:30 UTC
Labels: bug, confirmed
