### ISSUE TITLE
Transparent png bug with blur enabled

### ISSUE THREAD

**Issue by BobHasNoSoul** [jellyfin/jellyfin-web#1611] opened 2020-07-20 20:38 UTC
**Describe the bug**
This bug effects the images used on libraries if they are the .png format with a transparent background, making them look very odd with artifacts all over them in an attempt to get them to blur

**To Reproduce**
1. "Enable blurred placeholders for images" in the display settings 
2. Go to 'libraries'
3. Click on '...' button and then click 'edit images'
4. Click Browse 'Open a png file with a transparent background but a solid object in the foreground'
5. Click Upload
6. Open jellyfin's main library page and view the bug

**Expected behavior**
The transparent picture not to be blurred even when fully loaded when used on a library icon.

**Logs**
No relevant logs found relating to the issue

**Screenshots**

Please see attatched screen shot featuring the bug
![blur bug transparent](https://user-images.githubusercontent.com/23018412/87983960-20790880-cad1-11ea-9c4f-ce6a241d499f.PNG)

Please see attached screenshot after turning the blur function off 
![blur turned off transparent](https://user-images.githubusercontent.com/23018412/87984030-3dadd700-cad1-11ea-8565-d7e4be041c26.PNG)

**System (please complete the following information):**
 - OS: Debian
 - Browser: Chrome & Firefox & Android Chrome (possibly more)
 - Jellyfin Version: 10.6.0

**Additional context**
To get around this bug for now any user can simply turn off the blur images not fully loaded

**Comment by MrTimscampi** [comment] 2020-07-20 21:00
Unfortunately, there is no real fix for this and it's not really a bug, you're just not supposed to use transparent images there (While it shows something, there's a grey background to every card by default, even without without blurhash).

Blurhash doesn't support transparency, so even hiding it when loaded would look bad, and add more complexity to the code that handles image loading (Because you're have to listen for the animation end event, then filter down the results to what we want (because every animation throws these, then hide it), then do the opposite when images leave the screen).

Really, the proper fix here would be not using transparent images. The cards are made for non-transparent images (The overlay on mouse-over will cover the entire zone of the card anyway, for example).

**Comment by MrTimscampi** [comment] 2020-07-20 21:08
Note that, just like you hid the grey placeholders, you could use custom CSS to hide the canvas element in that particular section, which would fix this for you.

**Comment by Camc314** [comment] 2020-07-21 04:13
You could use custom css in the dashboard to hide the blurhash:
```
div[data-type="CollectionFolder"] canvas {
display: none;
}
```
And:
```
.cardBox:not(.visualCardBox) .cardPadder {
background-color: #00000000
}
```
to remove the grey background

**Comment by MrTimscampi** [comment] 2020-07-21 09:52
Closing, as this is not a bug and a workaround was provided.

**Closed by MrTimscampi** 2020-07-21 09:52 UTC
Labels: invalid
