### ISSUE TITLE
Copy Stream URL doesn't copy to clipboard

### ISSUE THREAD

**Issue by DarkVirtue** [jellyfin/jellyfin-web#657] opened 2019-12-30 19:28 UTC
**Describe the bug**
Using the "copy stream URL" option for a piece of media doesn't result in anything being placed in the clipboard

**To Reproduce**
1. Go to a media item, such as a TV show, in the web client.
2. Click on the hamburger menu.
3. Click "Copy Stream URL"
4. Pasting the clipboard contents shows the previous content, if any, not the streaming URL.

**Expected behavior**
Pasting after copying the stream URL should paste the stream URL.

**Logs**
The Jellyfin logs don't show an error when the option is chosen. However, the browser's console shows:
`document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler.`

**System (please complete the following information):**
 - OS: Debian 10
 - Browser: Firefox
 - Jellyfin Version: 10.4.3.0
 - Installed Plugins: Kodi Sync Queue, Playback Reporting, Reports, TMDb Box Sets
 - Reverse proxy: HAProxy

**Comment by MrTimscampi** [comment] 2020-01-06 11:18
For info, this is the part that needs to be worked on: https://github.com/jellyfin/jellyfin-web/blob/e376ddff084f7218621e4b6782f071e5a26d9c08/src/components/itemcontextmenu.js#L347

We could refactor the entire thing to use [clipboard-polyfill](https://github.com/lgarron/clipboard-polyfill) instead, which uses ES6 promises while handling compatibility with older browsers that don't have Async Clipboard API support.

**Comment by WX9yMOXWId** [comment] 2020-01-07 22:36
> We could refactor the entire thing to use [clipboard-polyfill](https://github.com/lgarron/clipboard-polyfill) instead, which uses ES6 promises while handling compatibility with older browsers that don't have Async Clipboard API support.

If I understand the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) correctly the recently introduced clipboard API only works on secure context. This means on `http` it would either fail or fallback to the current implementation which is the cause of this issue.

**Comment by JustAMan** [comment] 2020-01-10 16:25
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/557

**Closed by JustAMan** 2020-01-10 16:25 UTC
Labels: duplicate
