### ISSUE TITLE
Progress bar Icons flickering/layering on top of each other

### ISSUE THREAD

**Issue by thegreatanton** [jellyfin/jellyfin-web#5569] opened 2024-05-20 17:09 UTC
Hello everyone!

I was advised to post here (instead of "the Jellyfin forum").

_(PLEASE SEE ATTACHMENTS BELOW FOR A PICTURE OF THE ERROR)_

I have also included logs from my current setup. I don't know, if it is the right kind og logs - so do let me know if any other information is needed!
_(Content hidden by renaming files with "MEDIA NAME HIDDEN")_

[Log-5.txt](https://github.com/jellyfin/jellyfin-web/files/15379926/Log-5.txt)
[Log-4.txt](https://github.com/jellyfin/jellyfin-web/files/15379927/Log-4.txt)
[Log-3.txt](https://github.com/jellyfin/jellyfin-web/files/15379928/Log-3.txt)
[Log-2.txt](https://github.com/jellyfin/jellyfin-web/files/15379929/Log-2.txt)
[Log.txt](https://github.com/jellyfin/jellyfin-web/files/15379930/Log.txt)
<img width="1719" alt="Jellyfin_ERROR" src="https://github.com/jellyfin/jellyfin-web/assets/170354318/b7e0c596-bb95-4198-8f75-0ccd1a7a7f54">

**SETUP INFORMATION**

- Jellyfin version: 10.9.2

- OS: Debian 6.1 (physical PC)

- Issue (short): Progress bar bugged on web, Mac OS Viewer, and Android app. Icons appearing and flickering/layering on top of each other.

- Issue (long): Playing videos on the web player, Mac OS Jellyfin viewer, og Jellyfin Android appears to be broken. Multiple icons appear while muse/finger inputs occur. Icons flicker when the video is playing, but during a paused session, icons hover over the "timeline". No issues playing media on Jellyfin player through Apple TV. The issue first occurred today while upgradering to 10.9.2.

Thank you in advance!

**Comment by thornbill** [comment] 2024-05-20 19:08
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/5561

**Closed** 2024-05-20 19:08 UTC
Labels: bug, duplicate
