### ISSUE TITLE
Unstable - navigation elements disappear after leaving dashboard

### ISSUE THREAD

**Issue by solidsnake1298** [jellyfin/jellyfin-web#5180] opened 2024-02-03 21:27 UTC
**Describe The Bug**
When leaving the dashboard, the top navigation elements disappear.  I have to refresh the tab to restore navigation elements.

**Steps To Reproduce**
1. Go to Dashboard
2. Click on either the Jellyfin icon in the top right or click the back arrow icon

**Expected Behavior**
The navigation elements remain in place.

**Logs**
Nothing in server logs.

**Screenshots**
![Screenshot 2024-02-03 16 26 05](https://github.com/jellyfin/jellyfin-web/assets/137357145/6b4c5900-a7c6-4c29-b482-94d62dae0478)
![image](https://github.com/jellyfin/jellyfin-web/assets/137357145/85ca3765-b06d-416d-830e-4fb0ed46c65b)

**System (please complete the following information):**
 - Platform: Docker in Ubuntu 22.04.3
 - Browser: Chrome
 - Jellyfin Version: 10.9, jellyfin/jellyfin:20240126.4-unstable

**Comment by thornbill** [comment] 2024-02-03 21:32
Duplicate of #5033

**Closed** 2024-02-03 21:32 UTC
Labels: bug, duplicate
