### ISSUE TITLE
Playbar overlaps Album names on mobile

### ISSUE THREAD

**Issue by rexbron** [jellyfin/jellyfin-web#1110] opened 2020-04-19 22:26 UTC
**Describe the bug**

**To Reproduce**

1. Play a song
2. Go to Artist page
3. Click on an Artist
4. Scroll down to look at albums
5. Note the play bar obscures the album

NOTE: Artist must _not_ have a more like this bottom ribbon

**Expected behavior**
The play bar should not obscure the album

**Screenshots**
![Screenshot_20200419-181907](https://user-images.githubusercontent.com/587341/79701439-23165880-826b-11ea-97b5-3d755096ce95.png)

**System (please complete the following information):**
 - OS: Android 10
 - Browser: Android App
 - Jellyfin Version: 10.5.3

**Comment by MrTimscampi** [comment] 2020-04-23 15:38
Duplicate of #1090.

While the impacted screen is different, the root cause is the same.

**Closed by MrTimscampi** 2020-04-23 15:38 UTC
Labels: bug
