### ISSUE TITLE
Simplify Cast/disconnect dialog

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#910] opened 2020-03-08 22:47 UTC
The Cast interface would benefit from some streamlining. When the user presses the blue "Google Cast" icon on the top right the Cast ui is called upon. There are two unnecessary dialog boxes used to disconnect from the cast device.
![image](https://user-images.githubusercontent.com/61879508/76172437-53e37800-616c-11ea-8bcf-dda489e75e29.png)
![image](https://user-images.githubusercontent.com/61879508/76172440-59d95900-616c-11ea-9e99-a9e16e101a2f.png)
i recommend:
1) Completely doing away with the "shutdown confirmation."
2) Rename "disconnect" to "stop casting" to be more in line with guidelines and move that button to the "remote control" interface. Then do away with what remains.

**Comment by dkanada** [comment] 2020-03-09 02:42
This is a duplicate of another issue but I can't find it at the moment. We had a plan of action in that one.

**Comment by hamburglar2160** [comment] 2020-03-09 03:08
#671

**Comment by dkanada** [comment] 2020-03-13 06:53
Why was this reopened?

**Comment by hamburglar2160** [comment] 2020-03-13 11:47
> Why was this reopened?

As it turns out this issue is unique to Google Cast. Jellyfin's Native Cast (from this same interface) does not get a disconnect dialog.

Pressing "no" breaks things anyway.

This should probably be relabeled a bug.

**Comment by dkanada** [comment] 2020-03-14 05:10
The two issues are still the same subject though and neither one is unintended. You actually bring up a good point though, we should enable the same functionality on our native cast method as well.

**Closed by dkanada** 2020-03-14 05:10 UTC
