### ISSUE TITLE
Playing multiple episodes under "Latest TV Shows" does not play the first latest/unwatched

### ISSUE THREAD

**Issue by telans** [jellyfin/jellyfin-web#625] opened 2019-12-10 23:30 UTC
**Describe the bug**

When there are multiple episodes from the same show under "Latest TV Shows" (i.e they are grouped together), clicking on the group to play the first 'new/unwatched'  episode results in the first episode of the series being played.

I believe this is unintended, as playing a single episode starts the episode that was selected. I expect that playing multiple would start at the first episode that is grouped together. Screenshot of where this happens below.

**To Reproduce**

1. Go to "T.V Shows / Latest"
2. Click on a selection with multiple new/unwatched episodes. (has a blue circle)
4. See that the first episode of the series is shown, rather than the first unwatched episode.

**Expected behavior**

The first unwatched/new episode is played rather than the first in the series.

**Logs**

The logs just show the playing of the very first episode.

**Screenshots**

![Screenshot_20191211_122102](https://user-images.githubusercontent.com/45819748/70577853-fad36a80-1ba3-11ea-8cfe-4a7659c4899f.png)

**System:**

 - OS: Arch linux
 - Browser: Firefox v71
 - Jellyfin Version: 10.4.3

**Comment by telans** [comment] 2020-03-10 00:33
Still present

**Comment by Artiume** [comment] 2020-06-05 14:16
i'm not sure this can really be classified as a bug, if you're intending to play the next episode on deck, i'd expect the Up Next section to be used.

**Comment by MrTimscampi** [comment] 2020-06-05 14:25
The behavior here is consistent with what one would expect.

It is showing the series itself, not the two new episodes grouped. As @Artiume said, you'd use the Up Next section to play new episodes (Episodes failing to show up there would be a server issue).

One reason why it's setup this way is that new episodes might not be sequential. You might download things out of order. Hence the "Up Next" section, which is meant to show you what episodes you can watch now, based on what you've seen already.

I'm closing this since it's not actually a bug but expected behavior.

**Closed by MrTimscampi** 2020-06-05 14:25 UTC
Labels: bug
