### ISSUE TITLE
Full Featured Comic Book Reader

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin-web#1878] opened 2020-08-31 17:40 UTC
I thought I would mention here is a bit more featured Comic Book that has an MIT license and uses javascript like the epub reader.

https://github.com/afzafri/Web-Comic-Reader

**Comment by MrTimscampi** [comment] 2020-08-31 20:49
You already mentioned it in #1281 and I explained on Matrix why it is not a good choice for us (https://matrix.to/#/!NaLbfexyNIBQDbzGwB:bonifacelabs.ca/$x9ot6xf5-a0sr2QvG4IfyxWF_Fi2Qiq-P_u2lmV1gWE?via=bonifacelabs.ca&via=matrix.org&via=t2bot.io)

Quoting:

> I looked at uncompress.js back when I made the PR. It hasn't received any updates since 2018 and has less usage than libarchive.js. It also doesn't seem to support the Stream API, which is something we want (It allows us to start reading the comics before the CBR/CBZ is fully downloaded, which can take a while), it supports more formats and is generally faster due to relying on Web Assembly.
> 
> Downside is that we won't be able to provide comic reading on TVs, but I fail to find a usecase for reading comics on a TV anyway
> 
> jQuery is also very much a no-go, since we've been actively trying to take it out of the web client's source
> 
> It might seem like we often just push PRs without looking at what is available elsewhere, but we very much do. I looked at multiple existing comic readers to find things we could use, but wasn't happy with any of the options (bad structure, outdated technologies, technical debt, abandoned projects, etc).
> That essentially lead me to look at archive extractions libraries, where I looked at the few options available in a browser (being in a browser does limit our options compared to a node app), which lead me to choose libarchive.js for a few reasons:
> 
> * It supports the Stream API
> * It's based on libarchive, a well-known archive extraction library
> * It runs in web assembly
> * It supports more formats (We don't know if we'll need them, but it's there, so....)
> * It was still active

Essentially, what that means is that every option I have looked at (And if you look at #1281, I **did** start with existing options) wasn't suitable for various reasons and implemting our own solution from scratch is better for our needs than pillaging an existing project.

I'm closing this, as I consider it somewhat of a duplicate of #1281 and this has been addressed before.

**Closed by MrTimscampi** 2020-08-31 20:49 UTC
Labels: playback
