### ISSUE TITLE
Copy Stream URL Not Working in Firefox 70

### ISSUE THREAD

**Issue by person4268** [jellyfin/jellyfin-web#562] opened 2019-11-01 16:50 UTC
Clicking on a video and using the Copy Stream URL action doesn't actually copy anything and creates this warning in devTools: https://imgur.com/a/1ZvzLnj. 

**To Reproduce**
1. Go to any video
2. Open its dropdown
3. Open JS console in devTools
4. Click on Copy Stream URL
5. See warning

**Expected behavior**
The text appearing in the clipboard

**System:**
 - OS: Arch Linux
 - Browser: Firefox 70.0
 - Jellyfin Version: 10.4.0
 - Reverse proxy: Nginx

I'm using the Docker container if that makes any difference.

**Comment by anthonylavado** [comment] 2019-11-01 18:45
_transferred to jellyfin-web..._

**Comment by anthonylavado** [comment] 2019-11-01 19:58
Looks to be a duplicate of https://github.com/jellyfin/jellyfin-web/issues/557

**Closed by anthonylavado** 2019-11-01 19:58 UTC
Labels: bug, duplicate
