### ISSUE TITLE
Minify Jellyfin's JavaScript files

### ISSUE THREAD

**Issue by whalehub** [jellyfin/jellyfin-web#383] opened 2019-04-21 16:36 UTC
**Describe the feature you'd like**
I would like you to minify Jellyfin's JavaScript files in order to speed up the page's loading time and responsiveness. You can use UglifyJS 2 to accomplish this task.  

**Additional context**
Here's a report with detailed information about which files need to be minified: https://gtmetrix.com/reports/jellyfin.datahoarder.dev/nZYW8J98

**Comment by dkanada** [comment] 2019-07-04 22:22
This is a duplicate of #21 but you can always track our progress there.

**Closed by dkanada** 2019-07-04 22:22 UTC
Labels: duplicate
