### ISSUE TITLE
Artist images not loading in correctly

### ISSUE THREAD

**Issue by stankovictab** [jellyfin/jellyfin-web#4421] opened 2023-03-15 14:24 UTC
**Describe The Bug**

This is a duplicate of the issue I made on jellyfin/jellyfin, but I figured this might be a better place for it. 
https://github.com/jellyfin/jellyfin/issues/9419

First off, apologies if this issue is already documented, however I didn't find it.
The problem I have is that when I put images of an artist, specifically default.jpg, logo.png and backdrop.jpg, into the folder of my artist, and when I refresh the metadata, the images aren't loaded in when I go into his profile in the Jellyfin UI.
However, when I open one of his albums, the art refreshes, and I can see the backdrop and logo.
When I then go back into the artist from that screen, I have all the images loaded up.
When I return to the home screen and see all the artists, the artwork is gone.
This is pretty bizzare, and it's exactly the same problem on the Android Jellyfin app.

**Steps To Reproduce**

This is how the artist looks like in Home -> Music -> Artists.

![222234561-7e16fee1-ff06-45c2-b840-f079896853a9](https://user-images.githubusercontent.com/62820268/225337603-ddb8087c-acda-4288-8f3a-2d57cd84e34b.png)

This is the artist profile once you go in.

![222234851-9bdcc678-09b1-476d-a5a3-466b12b4bbb8](https://user-images.githubusercontent.com/62820268/225337689-9c04b25d-7ef5-4537-9fbe-bcf07e495153.png)

When you go into an album, all the artwork loads up instantly.

![222234928-ea0d08c4-36a4-484c-8b92-41e6134924a3](https://user-images.githubusercontent.com/62820268/225337759-d3eaf37f-6aab-4d02-ab5c-8cf0553ba049.png)

When you click the artist name from that screen you have the artist page with artwork.

![222235068-9ca47011-7da5-40aa-b9b6-2f3a3b3a6b46](https://user-images.githubusercontent.com/62820268/225337836-c4fd3460-d137-410f-ba70-5c8b283502ef.png)

And when you go back to home, it all goes away.

The Edit Images dialog on the artist is as you'd expect, when there's no artwork there's nothing there, when you load it up through the album it pops up.

It's almost like Jellyfin keeps two different versions of artist's metadata for some reason. 

I've tried it without the Skin Manager plugin, that is with the default skin, same thing.

**Expected Behavior**

The artist's images load up in the artists menu instantly. 

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.6.0]

```
- Jellyfin Version:Jellyfin.Server 10.8.9.0
- OS:Kubuntu 22.10
- Virtualization:None
- Clients:Browser
- Browser:Vivaldi (Chromium)
```

**Comment by thornbill** [comment] 2023-06-14 03:03
Looks like a duplicate of #3655

**Closed** 2023-06-14 03:04 UTC
Labels: bug, duplicate
