### ISSUE TITLE
Blured Artist and Album covers in 10.7.2

### ISSUE THREAD

**Issue by Maxplosion** [jellyfin/jellyfin-web#2590] opened 2021-04-12 20:01 UTC
**Describe The Bug**
Since the switch to 10.7.2 from 10.7.1 Album and Artist covers (EDIT: as well as detail pictures for Shows and Movies) are blured in detail view, seems like the blurhash is not resolved to the regular picture. Only those large Pictures, thumbnails are fine! 
Works in current version of Jellyfin Media Player. (see additional context for more)

**Steps To Reproduce**
1. open music library
2. select artist and go to detail page
3. see blured image (also not resolved after waiting)
4. click on album cover (which is shown correctly as thumbnail)
5. see blured album cover in details page 

**Expected Behavior**
non blured large images in detail screen. 

**Logs**
no specific log entries found.

**System (please complete the following information):**
 - Platform: Docker on QNAP NAS
 - Browser: Firefox, as well as Edge (for testing)
 - Jellyfin Version: 10.7.2

**Additional Context**
same happens in Edge as well as Firefox, but not in JF Media Player (v.1.3.0) as this one is according to the changelog still on 10.7.1 
* "Upgrade webclient to jellyfin-web 10.7.1."

**Comment by Maxplosion** [comment] 2021-04-12 20:03
Important addition, I just found out that this also happens for Shows and Movies, so not limited to only Music library.

**Comment by krutburken** [comment] 2021-04-12 20:22
Probably the same as #2587

**Comment by Maxplosion** [comment] 2021-04-12 20:29
It shows the poster, but only the blured version of it, in this issue it says the quality of the poster is lower than normal, but here there is only the blurhash shown. or did I missunderstand the issue in #2587 ?

**Comment by Maxplosion** [comment] 2021-04-12 20:59
last additional info: no issue on android app

**Comment by oddstr13** [comment] 2021-04-13 16:00
It more than likely the same issue, yes.
If you take a look at the network requests in the developer console when this happens, you'll likely see 400 status responses on the images, and decimal numbers passed in the fillHeight and fillWidth parameters.

Closing as duplicate of #2587

**Closed by oddstr13** 2021-04-13 16:00 UTC
Labels: bug

**Comment by Maxplosion** [comment] 2021-04-13 17:53
yes exactly, can see 400 bad request and fillWidth=546.75
