### ISSUE TITLE
"Recently Added in Movies" using backdrop instead of primary after PR 4825.

### ISSUE THREAD

**Issue by bradbeattie** [jellyfin/jellyfin-web#5041] opened 2023-12-02 22:09 UTC
**Describe The Bug**

https://github.com/jellyfin/jellyfin-web/pull/4825 caused a regression of images used on the homepage. Previously these were using the Primary image, but have started using the Backdrop image.

**Steps To Reproduce**

1. Visit `/web/#/home.html`
2. Note the aspect ratio of content in "Recently Added in Movies" et al.

**Expected Behavior**

Would have expected the Primary image to persist or some explicit call-out in the aforementioned PR if there was intent to change this behaviour.

**Screenshots**

![image](https://github.com/jellyfin/jellyfin-web/assets/54340/8d736ec0-0649-4b8c-b5e6-a04137e7c673)

**System (please complete the following information):**

 - Platform: Linux
 - Browser: Firefox, Chrome
 - Jellyfin Version: `jellyfin/jellyfin:unstable@sha256:54582302f75b174fb4312c34459b701285effa1ee7a50d7e1ae3973aadba7cd7`

**Comment by thornbill** [comment] 2023-12-02 22:52
Are you sure this is related to the web PR? I admittedly haven't dug into it too much, but I thought it was a server regression due to the capitalization change in https://github.com/jellyfin/jellyfin/pull/9764.

Related: https://github.com/jellyfin/jellyfin/issues/10657

**Comment by pokkst** [comment] 2023-12-04 17:57
Can confirm this is the same issue I'm experiencing: https://github.com/jellyfin/jellyfin/issues/10657

**Comment by thornbill** [comment] 2024-01-04 13:14
Should be fixed by https://github.com/jellyfin/jellyfin/pull/10702

**Closed by thornbill** 2024-01-04 13:14 UTC
Labels: bug
