### ISSUE TITLE
Network settings cannot be saved. Form control error produced...

### ISSUE THREAD

**Issue by lue30499** [jellyfin/jellyfin-web#3517] opened 2022-03-26 18:39 UTC
**Describe The Bug**
I cannot save the network settings. I get a `An invalid form control with name='' is not focusable.` in the browser console.
Please see [here](https://drive.google.com/file/d/1TKrXl-tmWQUqB2aiWF-XmMByGOi5Utzs/view?usp=sharing) for screen capture.

**Steps To Reproduce**
I do not know how to reproduce this on a freshly installed server. But mine does it.

**Expected Behavior**
To save the network settings.

**Logs**
Browser logs shown in the video provided.

**Screenshots**
Please see [here](https://drive.google.com/file/d/1TKrXl-tmWQUqB2aiWF-XmMByGOi5Utzs/view?usp=sharing) for screen capture.

**System (please complete the following information):**
 - Platform: Debian running in a proxmox lxc 
 - Browser: Firefox, Chrome
 - Jellyfin Version: 10.7.7

**Comment by gardner** [comment] 2022-03-28 07:21
This is a duplicate of #3440

**Closed** 2022-03-28 14:13 UTC
Labels: bug, duplicate
