### ISSUE TITLE
misaligned notifications icons and labels

### ISSUE THREAD

**Issue by ToXinE** [jellyfin/jellyfin-web#260] opened 2019-04-20 21:02 UTC
**Describe the bug**
misaligned div

**To Reproduce**
1. Go to Notifications

**Expected behavior**
icons and label should be aligned on the same row

**Screenshots**
![notifications](https://i.imgur.com/8VUA0Lg.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser:  Firefox
 - Jellyfin Version:  10.3.0]

**Additional context**
French version

**Comment by oddstr13** [comment] 2019-04-20 21:24
I just saw a similar issue elsewhere in the interface, and that was related to cached assets.
Doing a force reload of the webpage (skip cache), fixed the alignment there.

CTRL+F5 in FireFox

Try if that works

**Comment by dkanada** [comment] 2019-05-20 03:09
@ToXinE do you have a reliable way to reproduce this? I have seen it before but it resolved for me after the cache refresh @oddstr13 mentioned and I can't reproduce it anymore.

**Comment by ToXinE** [comment] 2019-05-20 14:23
not anymore in dashboard, it seems to be fixed with CTRL+F5. I stil lhave the bug in movies when clicking on subtitles icon. :'(

**Comment by dkanada** [comment] 2019-05-22 02:09
@ToXinE I don't see an open issue for the subtitle issue you mentioned. I am closing this issue since it must have been a cache problem, but feel free to open a new one for the subtitle icon.

**Closed by dkanada** 2019-05-22 02:09 UTC
Labels: bug
