### ISSUE TITLE
Some Images overlap episodes and even songs in now playing list

### ISSUE THREAD

**Issue by Raul824** [jellyfin/jellyfin-web#1508] opened 2020-07-03 13:22 UTC
Jellyfin version: 10.6
Build: Unstable
OS: Debian
Installation Type: Docker.

In some Tv Series, Movies and Now Playing lists in song the images overlap episode list or songs.
Below is a image from South park. Episode 1 and 2 are hidden behind the Image.

![image](https://user-images.githubusercontent.com/51978647/86473277-fa8afe80-bd83-11ea-9ec7-e2570f79231d.png)

**Comment by hamburglar2160** [comment] 2020-07-03 14:16
Likely a duplicate of #1507

**Comment by MrTimscampi** [comment] 2020-07-03 16:04
Indeed, closing this as it's a duplicate and is already fixed in an open PR.

**Closed by MrTimscampi** 2020-07-03 16:04 UTC
