### ISSUE TITLE
[issus].[?-10.8.0]: Chinese Web Font Bug.

### ISSUE THREAD

**Issue by TsLenMo** [jellyfin/jellyfin-web#3613] opened 2022-05-03 15:37 UTC
**Describe The Bug**

Path rendering is wrong in Simplified Chinese environment.

**Steps To Reproduce**

1. Go to 'Console'
2. See error

**Expected Behavior**

径

**Logs**

none

**Screenshots**

![image](https://user-images.githubusercontent.com/23328499/166485978-adff4270-2cf5-44c2-96b5-fbf278e5ace6.png)

**System (please complete the following information):**
 - Platform: [Windows 10 22H2]
 - Browser: [Edge]
 - Jellyfin Version: [10.8.0]

**Additional Context**

none

**Comment by thornbill** [comment] 2022-05-05 21:42
Is this a duplicate of #913?

**Comment by TsLenMo** [comment] 2022-05-06 03:11
> Is this a duplicate of #913?

Probably yes, I will close this Issue.

**Closed** 2022-05-06 03:11 UTC
Labels: bug
