### ISSUE TITLE
This client isn't compatible with the media and the server isn't sending a compatible media format.

### ISSUE THREAD

**Issue by SternumSteven** [jellyfin/jellyfin-web#5078] opened 2024-01-05 23:03 UTC
**Describe The Bug**
Jellyfin does not play any media files added to the library (on the server or any devices connected to the server).

**Media Information**
[log_20240105.log](https://github.com/jellyfin/jellyfin-web/files/13847383/log_20240105.log)
Attached due to the length of the file.

**Screenshots**
![image](https://github.com/jellyfin/jellyfin-web/assets/12756599/5e834989-5f63-4176-b47e-3452625e3e4b)

**System (please complete the following information):**
 - Platform: Linux Mint
 - Browser: Firefox
 - Jellyfin Version: 10.8.13

**Additional Context**
Just trying to set up a Jellyfin server on my laptop. Took a long time to scan the metadata but now nothing plays. I was able to watch one video file earlier on the laptop though.

**Comment by SternumSteven** [comment] 2024-01-05 23:34
![image](https://github.com/jellyfin/jellyfin-web/assets/12756599/a41ed0a1-b863-48dc-a79f-f6f28b1bb7c4)

I am also unable to change the path of ffmpeg.

**Comment by rndchris** [comment] 2024-01-22 20:45
This "not sending a compatible format" error message and the "file not found" messages in the error log indicate that this is probably a file system permissions issue. Check to make sure Jellyfin has the file  ystem permissions to read your media library. 

- If you're running Jellyfin in a Docker container, check that the user running the container has permission to access your media library folders.

- Otherwise, check that the Jellyfin machine user account, usually called 'jellyfin', has appropriate permissions to access your media library folders.

**Comment by thornbill** [comment] 2024-05-07 01:25
Duplicate of https://github.com/jellyfin/jellyfin-web/discussions/3410

**Closed** 2024-05-07 01:25 UTC
Labels: playback
