### ISSUE TITLE
Missing Scrolling support on WebOS

### ISSUE THREAD

**Issue by Barborica-Alexandru** [jellyfin/jellyfin-web#675] opened 2019-12-24 23:45 UTC
Hello, I'm not sure if this is the right place to report this. So I installed the IPK and it works just fine including streaming to the device from the jellyfin server, but the interface will not scroll. Essentially you are stuck with only the content that fits on screen making the interface pretty much unusable.

**Comment by JustAMan** [comment] 2020-01-09 13:12
@dmitrylyzo any ideas?

**Comment by Barborica-Alexandru** [comment] 2020-01-09 13:35
If it is because of jf-web i would imagine the problem is the web interface itself is not programed to keep focus and auto scroll based on currently selected object.

**Comment by MrTimscampi** [comment] 2020-01-09 21:18
I did a quick investigation (using WebOS 4).

The reason is because scrollManager is only enabled in a few cases. Enabling it on WebOS breaks the Magic Wheel on the remote (it doesn't scroll anymore), but the arrow navigation still works.

**Comment by dmitrylyzo** [comment] 2020-01-09 22:36
About WebOS 3 scroll issue:
https://github.com/jellyfin/jellyfin-web/pull/314#issuecomment-491590384
https://github.com/jellyfin/jellyfin-web/pull/544#issuecomment-546101744 (Experiment)

> Enabling it on WebOS breaks the Magic Wheel on the remote (it doesn't scroll anymore), but the arrow navigation still works.

ScrollManager just follows for the focused element. Mouse wheel works “in parallel” (if I remember), not taking into account that focusing on other element scrolls to it regardless to user scroll.

**Comment by JustAMan** [comment] 2020-01-10 14:13
@MrTimscampi how your mentioned PR fixes wheel? Or does it fix the magic wheel?

**Comment by MrTimscampi** [comment] 2020-01-11 11:03
@JustAMan It doesn't fix the Magic Wheel not working (The Magic Wheel just sends mouse scroll events... The scrollManager likely needs some more work for that) but it enables the scrollManager (which handles proper scrolling for the various weird browsers when using keyboard navigation) for the TV layout on all browsers (As the TV layout is the only one that really needs a scroll manager).

It at least allows proper navigation using the arrow keys on all remotes.

I found out that generally, the focus and scroll on the TV layout need a bit of work. It doesn't seem to make a switch between fully keyboard and mouse-based navigation.

I think a solution for this would be to add a few event listeners that look at mouse movements and arrow key inputs, then switch the scroll and focus manager on or off to allow for both navigation styles to work ?

**Comment by dmitrylyzo** [comment] 2020-01-11 12:07
ScrollManager does not (totally) prevent mouse wheel.
On PC, scroll by mouse wheel works.
On WebOS 4 and Tizen 5 emulators, it seems that mouse wheel is not handled by app (or engine).
But on real Tizen 4 TV with wireless keyboard, scroll by wheel works after some element has been focused by `mouseManager` (on hover).
Also, on WebOS 3 emulator, mouse wheel works, but there is an issue with inability to scroll the window <- this is why ScrollManager (and default focus) does not scroll.

WebOS 3 wheel scrolling:
![webos3-1](https://user-images.githubusercontent.com/56478732/72203942-5cc50f80-3483-11ea-8686-5e8d0d299cce.gif)

> I think a solution for this would be to add a few event listeners that look at mouse movements and arrow key inputs, then switch the scroll and focus manager on or off to allow for both navigation styles to work ?

I tried this https://github.com/jellyfin/jellyfin-web/pull/544#issuecomment-549043360, but didn't included to PR. This is a workaround for focus on hover of `mouseManager` (enabled on TV layout, but disabled on WebOS).

**Comment by JustAMan** [comment] 2020-01-13 08:14
@dmitrylyzo the issue you're showing in the gif seems to be at least partially caused by "headroom" thing which, if I'm not mistaken, we've disabled on non-mobile devices recently, maybe try with latest master?

**Comment by dmitrylyzo** [comment] 2020-01-13 11:31
@JustAMan GIF is 0bd50d67ec09a9e8553a6b6b3e9fa5869157b992
Checked 5b46f0263a6da91529c5869181e2d8ddd5dfb1a0 - same issue.

I still believe this is what @oddstr13 mentions https://github.com/jellyfin/jellyfin-web/pull/314#issuecomment-491590384

Checked in WebOS 3 browser (ScrollManager should be enabled in the same way as @MrTimscampi did in his PR, because browser in WebOS 3 not detected as "WebOS") - even wheel scroll properly works, but top menu sticked to viewport.

Also, I checked (on simple page) `window.scroll`, `window.scrollBy`, `document.documentElement.scrollTop`, `document.body.scrollTop`. None of them work in app mode, and I don't know why app engine and browser in the same emulator (v3) with the (supposed) same Chrome version work differently.
<details>
<summary>UserAgent strings</summary>

```
webOS 3 (app): Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.2.1 Chrome/38.0.2125.122 Safari/537.36 WebAppManager
webOS 3 (browser): Mozilla/5.0 (Linux; NetCast; U) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.31 SmartTV/6.0
```
</details>

**Comment by MrTimscampi** [comment] 2020-01-13 12:45
Generally, I think the browser detection should be improved a bit, especially in the case of Smart TVs.

**Comment by JustAMan** [comment] 2020-01-13 15:17
> I don't know why app engine and browser in the same emulator (v3) with the (supposed) same Chrome version work differently.

IIRC LG started to ship same engine for browser and for apps starting from 3.5 or so, this should explain the difference you're seeing.

**Comment by dmitrylyzo** [comment] 2020-01-25 22:42
@MrTimscampi warned me about using iframes. I configured proxy with `X-Frame-Options DENY`. So, bad news - in this case, my approach with "iframed" Jellyfin (in webos app) does not work. :disappointed:

The last option I have is to wrap Jellyfin content with a `div` (or use  an existing one) with `scrollY` class (I mentioned this before) - this allows to scroll by wheel and scrollManager. But in this case, top menu will become fixed (in webOS 3 it is already fixed), therefore it should be activated only for webOS 3.

_I also found that `webOS` object in webos app is just a wrapper for `window.PalmSystem` which is accessible from jf-web._

**Comment by JustAMan** [comment] 2020-01-27 13:09
> I configured proxy with `X-Frame-Options DENY`. So, bad news - in this case, my approach with "iframed" Jellyfin (in webos app) does not work. 😞

Then, like it goes in a joke, "don't do that" :) I mean, we can make a requirement for running stuff in WebOS app that your proxy doesn't deny `iframe`-s, doesn't look like a big deal to me tbh

**Closed** 2020-02-04 16:54 UTC
Labels: bug
