### ISSUE TITLE
Jellyfin 10.9.1 live tv not working anymore.

### ISSUE THREAD

**Issue by ckruijntjens** [jellyfin/jellyfin-web#5504] opened 2024-05-14 15:37 UTC
**Describe The Bug**
Jellyfin 10.9.1 live tv not working anymore. I use a m3u file with jellyfin. Not one channel is loading in live tv.

**System (please complete the following information):**
 - Linux Debian 12 lxd container
 - Browser: Chrome
 - Jellyfin Version: [10.9.1]

**Additional Context**
Jellyfin 10.9.1 live tv not working anymore. I reverted to version 10.8.13 and live tv is working again. Seems like a bug to me.

**Comment by thornbill** [comment] 2024-05-15 05:15
Seems like a duplicate of https://github.com/jellyfin/jellyfin/issues/11554

**Closed** 2024-05-15 05:15 UTC
Labels: duplicate, playback
