### ISSUE TITLE
Subtitle size won't change in Firefox

### ISSUE THREAD

**Issue by FelixSimonB** [jellyfin/jellyfin-web#6340] opened 2024-11-23 17:17 UTC
**Describe The Bug**
Setting the subtitle size doesn't affect on the actual player in Firefox

**Steps To Reproduce**
1. Go to Profile > Subtitles
2. Click on Text Size and Select Extra Large (desire size)
3. Play any movie/video
4. Subtitle size didn't changed.

**Expected Behavior**
Subtitle will be set on the settings and the changes will take effect on playback

**Screenshots**
Settings
![Image](https://github.com/user-attachments/assets/f525b2b4-e39f-4e4a-9e28-3b00aa2d7b04)

Playback
![Image](https://github.com/user-attachments/assets/31767b06-d6fa-4e86-9332-01275e1ae2f6)

**Comment by QuentinGG** [comment] 2024-11-26 22:57
I experience the same issue.

**Comment by dmitrylyzo** [comment] 2024-11-27 12:18
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/5602 (same reason).

**Closed** 2024-11-28 01:17 UTC
Labels: bug
