### ISSUE TITLE
mkv series playback bug after upgrading to10.8.3-1

### ISSUE THREAD

**Issue by cr0wm4n** [jellyfin/jellyfin-web#3790] opened 2022-08-04 20:51 UTC
**Describe The Bug**
I am trying to playback the Evil series, it worked fine on 10.7.0 but since upgrading today to 10.8.3-1 on ubuntu linux I am having issues playing single episodes from my computer using the chrome browser.

If I click play on a single episode I get the dreaded error...

Playback Error
This client isn't compatible with the media and the server isn't sending a compatible media format.

However,
If i select the season i want, then open the menu of the episode i want to play and select play all from here then the episode plays fine

using the Android app on my TV, I do not have this issue.

Exactly the same issue does occur on my iphone

**Comment by crobibero** [comment] 2022-08-05 22:53
Likely duplicate of https://github.com/jellyfin/jellyfin/issues/8205

**Closed** 2022-08-06 04:17 UTC
Labels: bug, duplicate
