### ISSUE TITLE
Filter are not remembered

### ISSUE THREAD

**Issue by MaDTaZ** [jellyfin/jellyfin-web#2644] opened 2021-05-01 16:01 UTC
**Describe the bug**
Filter will not keep each time you go to the library you have to set them again.  

**System (please complete the following information):**
 - OS: [Linux]
 - Virtualization: [Docker]
 - Clients: [All Formats.]
 - Browser: [All Browsers]
 - Jellyfin Version: [Version: 10.7.2]
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [NONE.]
 - Base URL: [None]
 - Networking: [Host]
 - Storage: [Local]

**To Reproduce**

1. Go to 'TVShow'
2. You have to enable the Filter all the time I like my library to only show unplayed

**Expected behavior**
For it remember the settings

**Comment by nkg447** [comment] 2021-07-04 11:12
Should the filter settings be saved for user or browser?

**Comment by SightSpirit** [comment] 2021-07-18 17:17
Ideally, I'd like filters to save per user session (or for there to be a setting for that). It is annoying filtering my music albums and losing the filter if I exit the library for any reason. But I usually want to start out a new browsing session with no filters, as my needs usually change from session to session.

Sounds like a job for cookies?

**Comment by MaDTaZ** [comment] 2021-07-18 17:39
i would like it for user once I set my filters I normally dont adjust them

**Comment by xF4m3** [comment] 2022-02-25 11:55
I also think this is a needed feature for any Media Server solution, the main thing we do is watching episodes we did not watch yet, so having user based Filters that are always enabled/remembered like unwatched/unplayed is kind of a must have. Having to siet by unplayed every time(in a Libary with 400+series) it takes about 5-10 seconds to load each time i change the filters.

Like @SightSpirit mentioned, a setting to say if it is only per session or always for user xyz would be a very good way to customize this or even a third option to disable the remembering completly would be nice to have.

I hope this does not get neglected :)

**Comment by cjhille** [comment] 2022-03-28 02:12
Alternatively the filter could be contained in the URL which would allow using a bookmark to save the state. IMHO there is no need to bundle it with a session if you can restore it in one click?

**Comment by rwjack** [comment] 2022-08-28 10:05
The URL option doesn't seem ideal for many libraries. Then we'd have to have 15 bookmarks for 15 libraries just to view unplayed content.

Think the cookie option is the way to go for filters.

It really is super annoying having to filter every time Jellyfin is opened.

**Comment by wookash** [comment] 2022-11-07 23:12
> The URL option doesn't seem ideal for many libraries. Then we'd have to have 15 bookmarks for 15 libraries just to view unplayed content.
> 
> Think the cookie option is the way to go for filters.
> 
> It really is super annoying having to filter every time Jellyfin is opened.

I second this. Just gave Jellyfin another chance thanks to the Cloudflare access option (I was and still am missing 2FA) and the fact that filters are being reset every time I'm refreshing or accessing a library page is very frustrating. In my view both options would work (i.e. session or user). To be honest I don't see any other major feature missing at the moment so hopefully this can be added soon ;)

**Comment by thornbill** [comment] 2022-11-13 23:13
Duplicate of #40

**Closed** 2022-11-13 23:13 UTC
Labels: enhancement, confirmed
