### ISSUE TITLE
Gif as Library thumbnail won't play anymore

### ISSUE THREAD

**Issue by Amasuke** [jellyfin/jellyfin-web#2528] opened 2021-03-27 15:52 UTC
**The Bug**
Before the upgrade to jellyfin 10.7 gifs would be animated when set as library thumbnails, now they are just static.

**Steps To Reproduce**

1. Edit images in library
2. upload animated gif
3. save
4. Thumbnail is not animated

**Expected Behavior**
The gif should be animated.

**Logs**
no log errors

**Screenshots**
no screenshots

**System (please complete the following information):**
 - Platform: Windows (Client), raspberry pi (server)
 - Browser: Firefox, Chrome, Edge (Chromium)
 - Jellyfin Version: 10.7.1

**Additional Context**
Same thing in the android app

**Comment by cvium** [comment] 2021-03-27 15:59
Duplicate of https://github.com/jellyfin/jellyfin/issues/5501

**Closed by cvium** 2021-03-27 15:59 UTC
Labels: bug
