### ISSUE TITLE
4 Music Bugs

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-web#1500] opened 2020-06-30 07:55 UTC
Bug #1 The Caravan palace album "<|°_°|>" will not display its name, the album and its image will show up, but with a missing name and no way to click into the album. I assume this will happen with any album named in this manor.

![image](https://user-images.githubusercontent.com/65789901/86099021-72b4a400-baa6-11ea-9f36-3e9f383f2e31.png)

Bug #2 Albums with multiple artists will pick one at random to display on a library page 
**To Reproduce**
Try any compilation album, say a monstercat one. 
Go to the album view in the library.
See how its just picked one of the artists as the full album artist

![image](https://user-images.githubusercontent.com/65789901/86099094-895afb00-baa6-11ea-8a7e-e67a93187131.png)

Bug #3 Some artists will not display alongside their song, despite being properly tagged.

![image](https://user-images.githubusercontent.com/65789901/86099149-a1cb1580-baa6-11ea-9003-6592c91a77ff.png)
![image](https://user-images.githubusercontent.com/65789901/86099206-b8716c80-baa6-11ea-9d47-d6c07ea64391.png)

Bug #4 If a song has too many artists, it will overflow offscreen, removing the options with it.
![image](https://user-images.githubusercontent.com/65789901/86099435-00908f00-baa7-11ea-9956-5ebf390c3a91.png)

 - OS:Windows 10
 - Browser: Firefox
 - Jellyfin Version: 10.5.5
**Additional context**

**Comment by MrTimscampi** [comment] 2020-06-30 10:12
To help us track bugs, please keep future reports to one bug per issue, thank you.

1 is a duplicate of #1428

2 is a likely a server-side issue (Albums with mutliple artists and without artists should be set to Various Artists or similar). Please open an issue on https://github.com/jellyfin/jellyfin/

3 needs more info. Where is the artist not showing?

4 is already fixed in master/unstable/10.6

**Comment by dkanada** [comment] 2020-06-30 10:13
The second might also be a web client issue. Perhaps we are using one of the artist objects for that field rather than the album artist.

**Comment by MrTimscampi** [comment] 2020-06-30 10:14
> The second might also be a web client issue. Perhaps we are using one of the artist objects for that field rather than the album artist.

We use `item.AlbumArtists[0]` for that text in all cases :)

**Comment by Darkwolf1515** [comment] 2020-06-30 10:27
> To help us track bugs, please keep future reports to one bug per issue, thank you.
> 
> 1 is a duplicate of #1428
> 
> 2 is a likely a server-side issue (Albums with multiple artists and without artists should be set to Various Artists or similar). Please look for a similar issue or open one on https://github.com/jellyfin/jellyfin/ if it doesn't exist
> 
> 3 needs more info. Where is the artist not showing?
> 
> 4 is already fixed in master/unstable/10.6

Sorry, I thought since they were all text display bugs it would be ok.

As for 3, in the first image, the album artist does not show up next to the song, like others do, but once played, shows up just fine in the now playing bar 


Doesn’t show up here:
![276D070B-ADD2-4055-AC7D-58F483A2E0CF]
(https://user-images.githubusercontent.com/65789901/86115905-6e29c480-ba81-11ea-8824-725d9d522c77.png)

But does here:
![D1092FA3-A861-49D7-BC50-DFBE3808BC61](https://user-images.githubusercontent.com/65789901/86116066-acbf7f00-ba81-11ea-8154-ad9258521c89.png)

**Closed** 2020-07-02 07:22 UTC
Labels: bug
