### ISSUE TITLE
Primary images in details view don't load on desktop if window width is indivisible by 4

### ISSUE THREAD

**Issue by rom4nik** [jellyfin/jellyfin-web#2595] opened 2021-04-15 14:04 UTC
**Describe The Bug**

Since 10.7.2, if the browser window has width indivisible by 4 and Desktop display mode is used, regular primary images do not load on the details page, resulting in only the blurred versions being visible.

**Steps To Reproduce**
1. Select Desktop display mode in display settings.
2. Resize browser window to a width indivisible by 4.
3. Go to a movie or TV show details page.
4. The primary image will not load, keeping the blurred version visible.

**Expected Behavior**
The blurred version of primary image is replaced with a regular image as soon as the latter is loaded, no matter the width of the browser window.

**Logs**
Nothing relevant in server logs.

Request (1202px width):
```json
{
	"GET": {
		"scheme": "https",
		"host": "redacted",
		"filename": "/Items/0537852174b6d8d7d4c55b220d9d510c/Images/Primary",
		"query": {
			"fillHeight": "451",
			"fillWidth": "300.5",
			"tag": "fe74a09f034e3eeea18bf660522e4e96",
			"quality": "90"
		},
		"remote": {
			"Adres": "redacted:443"
		}
	}
}
```

Response:
```json
{
	"type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
	"title": "One or more validation errors occurred.",
	"status": 400,
	"traceId": "00-b6a88a9bde4a924cb9bc91cd8adfeacc-78af3c28963edc4e-00",
	"errors": {
		"fillWidth": [
			"The value '300.5' is not valid."
		]
	}
}
```

**Screenshots**

1202px width:
![obraz](https://user-images.githubusercontent.com/46846000/114881244-1b987980-9e03-11eb-9380-b17e64809e86.png)

1200px width:
![obraz](https://user-images.githubusercontent.com/46846000/114881152-07547c80-9e03-11eb-92c9-a1ef9332bcc0.png)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox 87.0
 - Jellyfin Version: 10.7.2

**Additional Context**
This issue was not present in 10.7.1 and doesn't appear on mobile layout. Primary images in other places, e.g. front page and library page load and replace blurred ones correctly.

**Comment by cvium** [comment] 2021-04-15 15:02
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/2590

**Closed by cvium** 2021-04-15 15:02 UTC
Labels: bug
