### ISSUE TITLE
Jellyfin freezes randomly after clicking a button

### ISSUE THREAD

**Issue by azukaar** [jellyfin/jellyfin-web#3707] opened 2022-06-14 18:24 UTC
I am not sure exactly what's causing this but randomly while going to the setup, I get to a state where no buttons does anything anymore. There is then an error in the console.

**Steps To Reproduce**
I am using the latest 1.8.8, with Firefox, and Traefik 2

![image](https://user-images.githubusercontent.com/7872597/173661965-849aba53-9dda-4a5e-b040-36923051afcc.png)

**System (please complete the following information):**
 - Platform: Linux / Docker
 - Browser: Firefox
 - Jellyfin Version: 1.8.8

**Comment by thornbill** [comment] 2022-06-16 20:48
This appears to be a duplicate of https://github.com/jellyfin/jellyfin-web/issues/3521

**Closed by thornbill** 2022-06-16 20:48 UTC
Labels: bug, duplicate
