### ISSUE TITLE
Back button stops working

### ISSUE THREAD

**Issue by an0nfunc** [jellyfin/jellyfin-web#3710] opened 2022-06-15 19:17 UTC
**Describe The Bug**
After some traversing (e.g. going into a lib -> into a show/movie) the back button (in jellyfin, not the browser one) becomes unusable until reload and the error below is logged into the (js-)console.

**Steps To Reproduce**

1. Go into a show movie
2. Try to use "back"
3. Repeat until broken (do not reload page in-between)

**Expected Behavior**
Back should work.

**Logs**
```
Uncaught TypeError: e is undefined main.jellyfin.bundle.js:40841
    x main.jellyfin.bundle.js:40841
    replace main.jellyfin.bundle.js:40949
    _onpopstate main.jellyfin.bundle.js:41013
    x main.jellyfin.bundle.js:40841
    replace main.jellyfin.bundle.js:40949
    _onpopstate main.jellyfin.bundle.js:41013
    <anonymous> self-hosted:1115
```
which references
```javascript
'/' === e[0] && 0 !== e.indexOf(a) && (e = a + (i ? '#!' : '') + e);
```
in function
```javascript
function x(e, t, n) {
          var r = this.page = n || _,
          o = r._window,
          i = r._hashbang,
          a = r._getBase();
          '/' === e[0] && 0 !== e.indexOf(a) && (e = a + (i ? '#!' : '') + e);
          var s = e.indexOf('?');
          this.canonicalPath = e;
          var l = new RegExp('^' + a.replace(/([.+*?=^!:${}()[\]|/\\])/g, '\\$1'));
          if (this.path = e.replace(l, '') || '/', i && (this.path = this.path.replace('#!', '') || '/'), this.title = v && o.document.title, this.state = t || {
          }, this.state.path = e, this.querystring = ~s ? r._decodeURLEncodedURIComponent(e.slice(s + 1)) : '', this.pathname = r._decodeURLEncodedURIComponent(~s ? e.slice(0, s) : e), this.params = {
          }, this.hash = '', !i) {
            if (!~this.path.indexOf('#')) return;
            var c = this.path.split('#');
            this.path = this.pathname = c[0],
            this.hash = r._decodeURLEncodedURIComponent(c[1]) || '',
            this.querystring = this.querystring.split('#') [0]
          }
        }
```
If necessary I can probably build jellyfin-web without minimize.

**System:**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.8.0

**Comment by CommandStorm5** [comment] 2022-06-15 19:39
I would say more of a duplicate of #3705, same error and freezing behaviour.

**Comment by thornbill** [comment] 2022-06-16 20:49
This appears to be a duplicate of https://github.com/jellyfin/jellyfin-web/issues/3521

**Closed by thornbill** 2022-06-16 20:49 UTC
Labels: bug, duplicate
