### ISSUE TITLE
Latest Episodes row on homepage occasionally "resetting" and only showing one entry, when many should be there

### ISSUE THREAD

**Issue by viggy96** [jellyfin/jellyfin-web#2592] opened 2021-04-13 13:17 UTC
**Describe The Bug**
Basically title. The screenshots below should make the issue clear.

**Steps To Reproduce**

1. Add "latest episodes" to homepage.
2. Keep adding shows/episodes
3. Eventually, the latest episodes row resets to only showing one show or episode
4. Then it starts to fill up again as more shows/episodes come in.
5. Repeat

**Expected Behavior**
Latest episode row should show all valid entries

**Screenshots**
![image](https://user-images.githubusercontent.com/9837626/114558733-fc4df080-9c38-11eb-8d4f-63971d0b3c20.png)
![image](https://user-images.githubusercontent.com/9837626/114558780-08d24900-9c39-11eb-90cb-b0797b0b961e.png)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Chrome
 - Jellyfin Version: 10.7.1

**Comment by cvium** [comment] 2021-04-13 16:07
Wrong repo and duplicate of some server issue I can't remember the number of. Will link it later if I don't forget.

**Closed by cvium** 2021-04-13 16:07 UTC
Labels: bug
