### ISSUE TITLE
Why the video has been transcoded?

### ISSUE THREAD

**Issue by kamanwu** [jellyfin/jellyfin-web#3425] opened 2022-02-12 21:51 UTC
**Describe The Bug**

Jellyfin Web Version:  10.7.6

**The Video format is:**
```
Title1080p H264 SDR
CodecH264
AVCYes
ProfileHigh
Level41
Resolution1920x1080
Aspect ratio16:9
InterlacedNo
Framerate23.976025
Bitrate9553 kbps
Bit depth8 bit
Video rangeSDR
Pixel formatyuv420p
Ref frames1
NAL4
```

**The Audio format is:**
```
TitleEn - FLAC - Stereo - Default
Languageeng
CodecFLAC
Layoutstereo
Channels2 ch
Bitrate401 kbps
Sample rate48000 Hz
Bit depth16 bit
DefaultYes
```

**The container is MKV**

I use Chrome (window 10,) to play.  Based on : https://jellyfin.org/docs/general/clients/codec-support.html, The video should NOT be transcoded right?

**BUT I GET THIS**
The media is being converted into a format that is compatible with the device that is playing the media.
Framerate: 217fps
720 Kbps TS H264 AAC

Reason for transcoding:
VideoCodecNotSupported
AudioCodecNotSupported
ContainerBitrateExceedsLimit

**Expected Behavior**
 Video play directly.  No transcoding.
Did I do something wrong?

**Comment by JPVenson** [comment] 2022-02-12 22:10
Did you maybe set any Bitrate control? For that user or globally?

**Comment by kamanwu** [comment] 2022-02-12 23:09
> Streaming

No.  I did not set any Bitrate control.
I play on my local network.
If I use VLC/Windows Media Play to play the video directly, I did not see any issue.

**Comment by JPVenson** [comment] 2022-02-12 23:12
Could you post the Logfile and Transcoding log please?
https://YourAddressToJellyfin/web/#!/log.html
The "Log_Timestamp.log" and "FFMpeg.Transcode-Timestamp.log"

**Comment by kamanwu** [comment] 2022-02-12 23:15
Never mind,  when I try to use "Edge".  Video play directly. No transcoding.
So it might be my chrome's issue.

**Comment by JPVenson** [comment] 2022-02-13 13:39
@kamanwu That is great to hear the problem is resolved. Could you please close this issue?

**Comment by dmitrylyzo** [comment] 2022-02-13 15:33
It would be better to test this on 10.8.0. At least video shouldn't be transcoded, i.e. `Direct stream`.

If for some reason a player error occurs, JF tries to transcode audio, on the second error also video. :point_left: _Maybe errors in the browser console?_

**Closed** 2022-02-16 20:32 UTC
Labels: bug
