### ISSUE TITLE
How can I hide the OSD play bar at the bottom?

### ISSUE THREAD

**Issue by bombomtnt** [jellyfin/jellyfin-web#743] opened 2020-01-27 02:56 UTC
How can I hide the OSD play bar at the bottom when playing fast forward, rewind, and moving the mouse? Every time you perform an operation, the bottom and top will obstruct the screen, which greatly affects the viewing experience.

I only want the play menu bar to appear when the mouse moves to the bottom of the screen. Can this be achieved?

Chrome 79.0.3945.130 with x64 version.

**Comment by JustAMan** [comment] 2020-01-27 14:22
This is handled by jellyfin-web, so moved.

**Comment by ferferga** [comment] 2020-07-28 15:08
I don't think we should do that: most video players show the overlay whenever the mouse is moved inside the video container: changing that behaviour will only make things more confusing and unnecessarily complicated.

I'll tag this as discussion needed, but imho we should close this.

CC @jellyfin/web

**Comment by MrTimscampi** [comment] 2020-07-30 14:18
I agree with @ferferga, OSD is usually shown on any mouse movement. Changing this would confuse users.

I'm closing this as it is not a bug and feature requests should go to https://features.jellyfin.org

**Closed by MrTimscampi** 2020-07-30 14:18 UTC
Labels: discussion needed, enhancement
