### ISSUE TITLE
[Issue]: new activity screen is not readable

### ISSUE THREAD

**Issue by eythian** [jellyfin/jellyfin-web#5654] opened 2024-06-03 14:29 UTC
### Please describe your bug

The new activity screen (/web/#/dashboard/activity) is not useful as the columns are truncated and appear to not be resizeable. Mouseover works, but isn't a great interface. Perhaps they need to expand to fill the available screen, and wrap the content in the cells.

Additionally, this is even worse when accessing it from a phone. 

![image](https://github.com/jellyfin/jellyfin/assets/2203130/2d942130-3b43-4c8e-aca3-c61713e1a760)

### Reproduction Steps

1. On the web interface or via the Android app
2. Access the activity via Dashboard -> Activity
3. Note that useful information is truncated.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Linux
- Linux Kernel: 6.8.10-zabbly+
- Virtualization: none
- Clients: Android
- Browser: Firefox
- FFmpeg Version: n/a
- Playback Method: n/a
- Hardware Acceleration: n/a
- GPU Model: n/a
- Plugins: standard + playback reporting, open subtitles, subtitle extract, intro skipper
- Reverse Proxy: yes, nginx
- Base URL: /web/#/dashboard/plugins
- Networking: good
- Storage: plenty
```

### Jellyfin logs

```shell
No relevant logs
```

### FFmpeg logs

```shell
No relevant logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment] 2024-06-03 15:26
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/5524

**Closed** 2024-06-03 15:26 UTC
Labels: bug, duplicate
