### ISSUE TITLE
opening any page with "open link in new tab" leads to a broken page

### ISSUE THREAD

**Issue by 3n-k1** [jellyfin/jellyfin-web#1967] opened 2020-10-05 01:07 UTC
**Describe The Bug**
when clicking "open in new tab" (first screenshot) or middle-clicking any link, the page that opens is broken in some way (second screenshot). sometimes the page is a broken template, sometimes completely blank

**Steps To Reproduce**

1. open homepage (`https://jellyfin.whatever.com`)
2. notice the root redirects to `https://jellyfin.whatever.com/web/index.html#!/home.html
2. right-click any link, click "open link in new tab"
3. notice the new url is `http://jellyfin.whatever.com/web/movies.html?topParentId=foo`
4. see broken page

**Expected Behavior**
the link opens in a new tab with the correct rendering

**Screenshots**
![Screenshot_20200929_173634](https://user-images.githubusercontent.com/51172302/95031635-181e7b80-0685-11eb-8fe3-b6a1ac24514f.png)
![Screenshot_20200929_173635](https://user-images.githubusercontent.com/51172302/95031712-6895d900-0685-11eb-9806-8bac1ea4302d.png)

**System (please complete the following information):**
 - Platform: fFedora 32 (client and server)
 - Browser: firefox 81.0
 - Jellyfin Version: 10.6.4

**Additional Context**
manually changing the url to prefix it with `#!/` fixes the issue entirely

**Comment by thornbill** [comment] 2020-12-02 18:08
Duplicate of #1180

**Closed by thornbill** 2020-12-02 18:08 UTC
Labels: bug

**Comment by 3n-k1** [comment] 2020-12-02 20:17
ah, my apologies!
