### ISSUE TITLE
Quick Connect code not displayed in Spanish

### ISSUE THREAD

**Issue by psaintmalo** [jellyfin/jellyfin-web#4752] opened 2023-08-15 09:52 UTC
**Describe The Bug**
Requesting a quick connect code when the language is set in spanish results in the prompt without the actual quick connect code.

**Steps To Reproduce**

1. Go to User -> Display
2. Set the language to Spanish (Español)
3. Logout
4. Request a Quick Connect code

**Expected Behavior**
The quick connect code should be displayed in the prompt

**Actual behvaiour**
The quick connect code is not displayed in the prompt

**Screenshots**
![Screenshot 2023-08-15 113509](https://github.com/jellyfin/jellyfin-web/assets/13824202/5da686b8-f87c-4eb2-b1b2-b33a2317108c)
![image](https://github.com/jellyfin/jellyfin-web/assets/13824202/79f91c61-ae60-4d27-9c10-743f8f17848b)

**System:**
 - Platform: Have checked and reproduced in Windows (Browser), Windows (App) and Tizen.
 - Browser: Firefox
 - Jellyfin Version: 10.8.10

**Additional Context**
Looking at the network activity when making the request, the code is received, but is never displayed. If I take the code from the network requests panel and input it, I will log in succesfully, so the only step of the process that fails is the formatting of the string to include the code.

The locale for the Quick Connect string for Spanish as in src/strings/es.json is the following: 
`"QuickConnectAuthorizeCode": "Introducir código de identificación {0}"`

**Comment by thornbill** [comment] 2023-08-15 10:05
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/4540

**Closed** 2023-08-15 10:06 UTC
Labels: bug, duplicate
