### ISSUE TITLE
Playback error after upgrading to 10.8.3

### ISSUE THREAD

**Issue by michaeldduffield** [jellyfin/jellyfin-web#3787] opened 2022-08-02 16:30 UTC
**Describe The Bug**
Some files which were previously playing (under 10.8.1) now result in a playback error ("This client isn't compatible with the media and the server isn't sending a compatible media format.")

**Steps To Reproduce**
1. Select a video to play in the web client
2. Some videos will play correctly, whilst others result (almost immediately) in the error mentioned above

**Expected Behavior**
These videos were playing correctly previously, so it's expected that they should continue to play correctly

**Screenshots**
<img width="372" alt="Screen Shot 2022-08-03 at 1 54 05 am" src="https://user-images.githubusercontent.com/10044370/182425571-9ffefeea-8288-4ea8-a268-3f0cbd8a7568.png">

**System (please complete the following information):**
 - Platform: Mac OSX
 - Browser: Chrome (and Firefox also tested)
 - Jellyfin Version: 10.8.3

**Additional Context**
The videos I've immediately noticed this occurring with are mkv files (H264 or HEVC codec). I have found a mp4 (H264 codec) which appears to play correctly.

**Comment by GermanCoding** [comment] 2022-08-02 16:48
I have the same issue. To further clarify, this is actually a regression since 10.8.2, which also exists in 10.8.3.

I cannot identify a clear pattern which medias have issues. I mostly encounter broken H.265 episodes (.mp4) with subtitles, but a few movies with H.265 (.mp4) and subtitles work fine. No idea.

I'm also not sure whether this is web client related or something server-side.

**Comment by michaeldduffield** [comment] 2022-08-02 17:02
Not sure if this is related or not, but I'm seeing an `Uncaught (in promise) undefined` error in the console logs which appears to occur at the same time a selecting a video where this error is seen. There don't appear to be any errors in the server logs which I can see.

<img width="1182" alt="Screen Shot 2022-08-03 at 2 30 43 am" src="https://user-images.githubusercontent.com/10044370/182432541-4c2df3a5-9bde-442c-b643-abb71bf5413e.png">

**Comment by jainal09** [comment] 2022-08-02 17:08
Having the same issue after upgrading to docker jellyfin/jellyfin:latest

**Comment by timawesomeness** [comment] 2022-08-02 20:32
Having the same issue, also affects Jellyfin Media Player for me, not just the web client.

[Some users on reddit say it's only an issue when watching from an admin account](https://www.reddit.com/r/jellyfin/comments/wdxrpt/take_two_hotfix_1083_is_out/iimxzuu/?context=10000).

**Comment by mosauter** [comment] 2022-08-04 19:32
> Having the same issue, also affects Jellyfin Media Player for me, not just the web client.
> 
> [Some users on reddit say it's only an issue when watching from an admin account](https://www.reddit.com/r/jellyfin/comments/wdxrpt/take_two_hotfix_1083_is_out/iimxzuu/?context=10000).

Using a different account did not help me. With both the web client and the jellyfin-media-player I still get the same error that @michaeldduffield mentioned above.

Kodi as a player frontend works like a charm though with either account.

**Comment by cr0wm4n** [comment] 2022-08-04 21:04
i just posted a bug similar, but for mkv series seasons.. hitting play on an episode has this issue but if i open the menu and select play all from gere then it plays fine

**Comment by toby3d** [comment] 2022-08-05 16:49
> hitting play on an episode has this issue but if i open the menu and select "play all from here" then it plays fine

It didn't work in either the TV client or the browser client.

> [Some users on reddit say it's only an issue when watching from an admin account](https://www.reddit.com/r/jellyfin/comments/wdxrpt/take_two_hotfix_1083_is_out/iimxzuu/?context=10000).

Creating a new user with minimal viewing rights works.

**Comment by thornbill** [comment] 2022-08-06 04:18
Looks like a duplicate of https://github.com/jellyfin/jellyfin/issues/8205

**Closed** 2022-08-06 04:18 UTC
Labels: bug, duplicate
