### ISSUE TITLE
Player settings do not appear if the video is not being transcoded on 10.8 Beta 3

### ISSUE THREAD

**Issue by striker72199** [jellyfin/jellyfin-web#3656] opened 2022-05-18 16:44 UTC
**Describe The Bug**
On Edge, if the video is not being transcoded, there is no gear icon to open the settings for the player. If the video is being transcoded, the gear icon with settings does show up. This issue does not appear for other browsers like Chrome or the android app.

**Steps To Reproduce**
Play any direct play video on the Edge browser.

**Expected Behavior**
The gear icon to appear if the video is not transcoding.

**Screenshots**
No gear icon:
![image](https://user-images.githubusercontent.com/4231110/169097043-86c62d9f-cf5e-4285-88cd-0bd1f5e2df7a.png)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Edge
 - Jellyfin Version: 10.8 Beta 3

**Comment by lifehackerhansol** [comment] 2022-05-22 05:36
I have this issue on every platform as long as it's Jellyfin's official client, be it Jellyfin Media Player (Windows and Linux), Jellyfin Android, Edge or Firefox. (All of my Android devices do this as well; I'm not sure why yours does not.) I don't have any iOS devices to test from there.

After some discussion over at Matrix, it seems this was an intentional change. Looking through the changelogs I think this was actually intended behaviour all the way back from Emby, and it showing up was unintentional until a certain PR to the main repo fixed it (perhaps 7699?) Though really I consider this a feature and not a bug D:

**Comment by striker72199** [comment] 2022-05-22 05:53
> After some discussion over at Matrix, it seems this was an intentional change. Looking through the changelogs I think this was actually intended behaviour all the way back from Emby, and it showing up was unintentional until a certain PR to the main repo fixed it (perhaps 7699?) Though really I consider this a feature and not a bug D:

I don't understand why this would be intentional. Without player settings, it is not possible to do things as simple as adjust the subtitle timings.

**Comment by lifehackerhansol** [comment] 2022-05-22 06:03
So the reasoning was that the video was not transcodeable. If so, the whole setting button is hidden.

Which seems very wrong: I use a GTX 1060 for transcoding, and I'm very certain my graphics card can transcode a `1080p H264 SDR` video, and more. So I think what constitutes as "not transcodeable" seems to be broken.

This was without looking at any code, because I don't know how to write C#. So all a hypothetical guess. The reasoning behind why the settings icon should be hidden entirely makes sense to me, but it seems that reasoning is currently bugged.

**Comment by dmitrylyzo** [comment] 2022-05-22 10:40
I have reproduced this on Chrome if video is DirectPlay.
The server probably incorrectly reports `SupportsTranscoding`.

1. Open DevTools (F12 ?)
2. Open Network tab
3. Run the playback
4. Search `/PlaybackInfo`
5. What the value of `MediaSources / [0] / SupportsTranscoding`?

**Comment by lifehackerhansol** [comment] 2022-05-22 14:21
Mine doesn't exist?

```
http://192.168.1.5:8096/Items/242cae07a76e6360b5b8143a988342a8/PlaybackInfo?UserId=352636bdcbc149968875ea43fedc8943&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000
```
What's weirder is I don't have a max bitrate set yet there is one...

**Comment by dmitrylyzo** [comment] 2022-05-22 14:29
> Mine doesn't exist?

Click it and look in the `Preview` sub-tab. _(I've updated that post.)_

> What's weirder is I don't have a max bitrate set yet there is one...

afaik, the maximum bitrate is added by default according to the device.

**Comment by lifehackerhansol** [comment] 2022-05-22 15:16
`SupportsTranscoding` is indeed false. Took me a moment to find what you meant since `Preview` isn't a thing on Firefox apparently. (Had to look at the JSON response)

**Comment by dmitrylyzo** [comment] 2022-06-15 20:57
Fixed by https://github.com/jellyfin/jellyfin/pull/7784
Also #3668 helps

**Closed by dmitrylyzo** 2022-06-15 20:57 UTC
Labels: bug, ui & ux
