### ISSUE TITLE
Jellyfin iOS webapp - side menu scroll immediately closes side menu 10.8.9

### ISSUE THREAD

**Issue by elapse2039** [jellyfin/jellyfin-web#4299] opened 2023-01-23 12:21 UTC
**Describe The Bug**
After upgrading server jellyfin 10.8.8 to 10.8.9 the iOS side menu cannot be scrolled.

scrolling action makes the side menu immediately close before anything can be selected.

If you dont scroll you can select a side menu item. If it is off screen and you need to scroll there is no way to reach it.

**Steps To Reproduce**
Open side menu, attempt to scroll down.

**Expected Behavior**
Scroll up and down side menu and make a selection, then side menu closes.

worked fine in 10.8.8 previous release. Started happening immediately after 10.8.9 upgrade.

**Logs**
Cannot get iOS logs.

**System (please complete the following information):**
 - Platform: iPhone
 - Browser: jellyfin app
 - Jellyfin Version: 10.8.9

**Comment by elapse2039** [comment] 2023-01-23 12:24
I just noticed this was only on admin dashboard and if I kill and restart the app the side menu now behaves normally and I cant reproduce it.

**Comment by thornbill** [comment] 2023-02-10 13:14
Closing since you are unable to reproduce the issue. 👍

**Closed** 2023-02-10 13:14 UTC
Labels: bug
