### ISSUE TITLE
Long lists of artists do not push down track list

### ISSUE THREAD

**Issue by therealmelee** [jellyfin/jellyfin-web#4680] opened 2023-06-08 15:23 UTC
**Describe The Bug**
When looking at an Album with a large number of associated artists, the list of artists ultimately flows down and on top of the track list.

**Expected Behavior**
Track list frame should start no fewer than X pixels below the bottom of the contents of the album/artist frame.  

**Screenshots**
![Screenshot 2023-06-08 16 21 44](https://github.com/jellyfin/jellyfin-web/assets/56363525/0effa30e-e2db-417d-b25d-ec21b1b4e85a)

**System (please complete the following information):**
 - Platform: Server - Linux. Client CrOS
 - Browser: Chrome
 - Jellyfin Version: 10.8.10

**Comment by therealmelee** [comment] 2023-06-08 15:24
Looking at the screenshot, I think the play/instant mix/shuffle/favorite buttons perhaps also should be repositioned?

**Comment by thornbill** [comment] 2023-07-10 05:55
Duplicate of #4228

**Closed** 2023-07-10 05:56 UTC
Labels: bug, duplicate
