### ISSUE TITLE
UI lagging in Chrome when scrolling movie list after update to 10.4.1

### ISSUE THREAD

**Issue by drikqlis** [jellyfin/jellyfin-web#570] opened 2019-11-09 16:07 UTC
**Describe the bug**

After updating Jellyfin to 10.4.1 when scrolling trough movie list in poster mode with 100 movies on one page UI is lagging in Chrome and Chromium. Additionally CPU and GPU usage spikes to 20-25% on i7 8700K and RTX 2080 but i don't know if it is to be expected. In Firefox problem is not present but high usage spikes are still visible. Tested on 2 different PCs in Chrome, Chromium and Firefox.

**To Reproduce**

1. Start Jellyfin in Chrome or Chromium.
2. Go to list of movies with 100 movies on poster mode.
3. Start scrolling.
4. UI will be lagging.

**Expected behavior**

UI should still be buttery smooth like on 10.4.0.

**Logs**

I don't know if it is related but this shows up a lot in logs. I changed the Base URL like showed in release readme.
```
[2019-11-09 16:55:56.877 +01:00] [ERR] Could not find handler for "/socket"
[2019-11-09 16:55:56.877 +01:00] [ERR] Error processing request: "Unable to find the specified file."
```
**System (please complete the following information):**
 - Jellyfin OS: Ubuntu 18.04.2 LTS
 - Browser: Chrome, Chromium, Firefox
 - Jellyfin Version: 10.4.1

**Additional context**

OS on test machines is Windows 10. Firefox and Chrome are updated.

**Comment by dkanada** [comment] 2019-11-09 16:41
Do you use a reverse proxy?

**Comment by drikqlis** [comment] 2019-11-09 16:44
Yes, NGINX, but i tried without proxy and the effect is the same.

**Comment by r00z3r** [comment] 2019-11-10 11:39
Same answer as https://www.reddit.com/r/jellyfin/comments/du2ih4/jellyfin_behaves_very_sluggishly_on_a_library/

Seems to be a bug introduced in v10.4.1

Can you try to rollback to v10.4.0 and confirm ?

10.4.0 :

http://<ip>:8096/Items/<hash>/Images/Primary?maxHeight=274&maxWidth=183&tag=<tag>&quality=90

10.4.1 :

http://<ip>:8096/Items/<hash>/Images/Primary?tag=<tag>&quality=90

Thanks

**Comment by dkanada** [comment] 2019-11-10 11:44
Yeah this is likely the maxWidth removal, I wonder why Chrome gets hit so hard? We can fix this by adding that value back to the card builder.

**Comment by r00z3r** [comment] 2019-11-10 12:52
That would be great to add the values back to the card builder, because this consume much more CPU & bandwidth without the max values.
Thanks!

**Comment by joshbali** [comment] 2019-11-17 01:06
Replacing the card builder scripts from with the 10.4.0 versions seems to work as a temporary solution.
Tested on Debiab 10 (1.1 GHz, 8GB RAM) with no issues so far).

**Comment by joshuaboniface** [comment] 2019-11-24 19:18
It looks like what happened was that 10.4.1 build against the WebUI's `master` branch, at least on Debuntu. So you got a change that shouldn't have been in the release branch.

This *should* be fixed on 10.4.2 by virtue of the change that caused it no longer being present. It will still affect `master` though.

**Comment by drikqlis** [comment] 2019-11-25 00:47
Can confirm it is fixed on 10.4.2 on Chrome and Chromium.

**Comment by joshbali** [comment] 2019-11-25 01:17
Confirmed. Works as expected again on 10.4.2.

**Closed** 2019-11-25 04:20 UTC
Labels: bug, confirmed, regression

**Comment by JustAMan** [comment] 2019-11-25 11:30
We have to find out what broke it in master though...
