### ISSUE TITLE
UI is missing when a user's password is changed by the admin.

### ISSUE THREAD

**Issue by Tsumuri-u** [jellyfin/jellyfin-web#5644] opened 2024-06-01 05:37 UTC
**Describe The Bug**
When a user is logged into a Jellyfin instance and the admin changes said user's password, the user's UI will be stuck on a mostly-empty page with no means of logging in or changing their password. The user's browser data (or the config files for Jellyfin Media Player) must be deleted to prompt another login.

**Steps To Reproduce**
1. Have the user log in to the Jellyfin UI, either via Web or via Jellyfin Media Player.
2. As an admin, change the user's password.
3. Have the user attempt to access Jellyfin.

**Expected Behavior**
The user whose password has been changed should be prompted with a login screen instead of attempting to display a UI.

**Screenshots**
<img width="640" alt="image" src="https://github.com/jellyfin/jellyfin-web/assets/68445671/d16844f7-167f-4991-a736-d368f6a87bcc">

**System:**
 - Platform: Windows
 - Browser: Chrome, Firefox
 - Jellyfin Version: 10.9.3 (Server), 10.9.3 (Web), 1.10.1 (Media Player).

**Comment by thornbill** [comment] 2024-06-01 06:02
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/5626

**Closed** 2024-06-01 06:02 UTC
Labels: bug, duplicate
