### ISSUE TITLE
Need dynamic page updates

### ISSUE THREAD

**Issue by classicjazz** [jellyfin/jellyfin-web#757] opened 2020-02-02 00:45 UTC
**Describe the bug**
Pages are not automatically updated, unlike Plex, etc.

**To Reproduce**
For example,
(1) Cancel a series recording
- confirmation dialog box then series jacket art remains until you refresh the browser

(2) Delete an episode recording
- confirmation dialog box. Episode jacket art remains until you refresh the browser

**Expected behavior**
Cancelled series / deleted episodes would be automatically removed from the current view without refreshing the web browser.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Docker on Synology
 - Browser: Firefox, Chrome, Safari
 - Jellyfin Version: 10.4.3

**Additional context**

**Comment by JustAMan** [comment] 2020-02-12 16:02
How come it's a bug? More like a feature request...

**Comment by dkanada** [comment] 2020-02-12 16:03
Some components have dynamic updates, but you're right that a lot of pages don't get any at all.

**Comment by classicjazz** [comment] 2020-02-12 16:04
Because deleted episodes remain visible in the user interface. Users are left uncertain whether command failed or not. Subsequent attempts to delete the still visible but already deleted asset fail.

**Comment by classicjazz** [comment] 2020-04-03 22:06
Also, this impacts the iOS client (and presumably the Android one). On smartphone apps, dynamic updates are assumed. And there is no easy way to refresh the page, like in a desktop web browser.

**Comment by xelivous** [comment] 2020-07-10 18:07
Pages are still not dynamically updated.

Please remove this terrible stale bot that exists to just boost up "closed" issue metrics while obfuscating what actually needs to still get done.

**Comment by anthonylavado** [comment] 2020-07-10 18:43
@xelivous What metrics could we possibly care about? Remember we are a volunteer group of, at most, 36 people listed in the organization, of which a smaller set are active, of which an even smaller set actually "work", for free and in their spare time, on the web repository?

Remembering that we have an estimated 15,000+ installs, which is probably even lowballing it.

The Stalebot is around to help prevent issues from literally getting stale. Not every issue is a problem, and not every issue opener responds when we ask for more information/respond with a fix/etc.

I'm sorry we missed the "keep this open/confirmed" tag on this one. Please consider that there have been 2,499 issues (both open and closed) across the main server repository and this one (arguably the two core parts of a Jellyfin install), since December 8, 2018 (or roughly 19 months). Add a combined 2,403 pull requests (open and closed/merged) on top of that too.

We don't care about metrics. We're just trying to stay organized.

**Comment by MrTimscampi** [comment] 2020-07-30 14:46
Closing this as it's indeed a feature request and these now live on https://features.jellyfin.org/.

**Closed by MrTimscampi** 2020-07-30 14:46 UTC
Labels: confirmed, enhancement, ui & ux
