### ISSUE TITLE
Unreasonable amount of request sent when reversed proxied by caddy

### ISSUE THREAD

**Issue by jakanaka** [jellyfin/jellyfin-web#5176] opened 2024-01-30 04:43 UTC
**Describe The Bug**
I have jellyfin stable reverse proxied by caddy. When i goto the login page with the domain (https), jellyfin sends around 1500 requests and downloads bunch of fonts. This does not happen when connected locally or even with ip address.

**Steps To Reproduce**
1. Reverse proxy jellyfin through caddy. I used the config from jellyfin doc
2. Open a private window in the browser
3. Open network tab and goto the domain (https)
4. Inspect the network requests

**Screenshots**
![image](https://github.com/jellyfin/jellyfin-web/assets/92713678/57bd9aaf-6fb2-4340-ba10-a8e218fc69e9)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Chrome
 - Jellyfin Version: v10.8.13, v10.8.11

**Comment by thornbill** [comment] 2024-01-30 13:56
Seems like a duplicate of https://github.com/jellyfin/jellyfin-web/issues/4549

**Closed** 2024-01-30 13:56 UTC
Labels: bug, duplicate
