### ISSUE TITLE
[Bug] People Images don't display from .nfo files

### ISSUE THREAD

**Issue by neo-neo1** [jellyfin/jellyfin-web#3217] opened 2021-12-10 07:17 UTC
**Bug Use Case Conditions:**
Since Sonarr/Radarr creates metadata I disabled all metadata options in Jellyfin's Movies/Shows Library options. Jellyfin-Web uses all existing nfo & image metadata properly besides People (Cast & Crew) images. Actor name text is shown but not image.

<img width="204" alt="ScreenShot 2021-12-10 at 12 44 55 AM" src="https://user-images.githubusercontent.com/6996362/145526495-b9381fe6-4db6-4084-a0ac-27bd1ff59f8f.png">

**Actor metadata field created by Sonarr/Radarr in .nfo file**
```
  <actor>
    <name>Arnold Schwarzenegger</name>
    <role>John Matrix</role>
    <order>0</order>
    <thumb>https://image.tmdb.org/t/p/original/z6IbTtI2FWAVZE6b1V4mqEHjwO6.jpg</thumb>
  </actor>
```

**Here's the catch:**
If I click on placeholder image the detailed actor page opens & properly displays same image from .nfo file's actor field (as it should).

<img width="404" src="https://user-images.githubusercontent.com/6996362/145528382-a20cb45c-eaa4-4273-b6b4-20389607a483.jpg">

When this occurs displayed image is saved in `/data/metadata/people/A/Arnold Schwarzenegger/folder.jpg`

Now if I go back to the original problem page image now displays properly, instead of place holder:

<img width="204" src="https://user-images.githubusercontent.com/6996362/145529000-3a5fd6c5-ddfb-4cf4-a9c6-92ffdd29da22.jpg">

Thus, People (Cast & Crew) images do not display from `<thumb>https://image.tmdb.org/t/p/original/z6IbTtI2FWAVZE6b1V4mqEHjwO6.jpg</thumb>` in .nfo files. Instead, they get saved to disk only when you click on the missing placeholder image.

**Problems & Solutions:**

- One potential solution is an option to save all people images from .nfo file links to disk automatically upon library scans, however this does NOT happen. Only clicking upon missing placeholder images saves it to disk. Should we click on every missing place holder image as a work around fix? There is thousands of them. Scanning library for `Search for missing Metadata` or `Replace all metadata` does nothing. Triggering `Refresh People` in `Scheduled Task` also does nothing.
- Another solution would be Jellyfin-Web to display People images directly from .nfo file http links if they exist. This would eliminate duplicity of saving images to disk instead of displaying from .nfo http field links when they exist.

**Additional Thoughts:**
- Since Sonarr/Radarr create metadata, I use it. They provide all needed metadata for my Kodi & Jellyfin devices. I hope I won't need to redundantly enable Jellyfin to also create metadata in addition to Sonar/Radarr. Ideally Jellyfin-Web should display existing People image links from .nfo files.

**System (please complete the following information):**
 - Platform: Armbian Buster
 - Browser: Firefox 94.0.2 on macOS
 - Jellyfin Version: 10.7.7

**Comment by dannymichel** [comment] 2022-04-26 09:04
Have you figured something out for this? I have the same issue exactly as you described it.

**Comment by neo-neo1** [comment] 2022-08-25 02:16
Still exists.

**Comment by thornbill** [comment] 2022-08-27 18:04
This isn’t specific to nfo files and isn’t an issue with jellyfin-web. When actors first get created in the server they only exist in a partial state. Images are not loaded until certain requests are made. It’s a bit of a weird issue. There is at least one issue in the server repo for it so I’ll close this one as a duplicate of https://github.com/jellyfin/jellyfin/issues/8288.

**Closed by thornbill** 2022-08-27 18:04 UTC
Labels: bug
