### ISSUE TITLE
Current password field in Profile settings absolutely does not work

### ISSUE THREAD

**Issue by EvgeniyDoctor** [jellyfin/jellyfin-web#4326] opened 2023-02-04 17:21 UTC
**Describe The Bug**

In profile settings i can press save under **empty** password fields and my current password will be erased.

**Steps To Reproduce**

1. Go to profile settings
2. Click on **Save** under empty password fields. It does not matter if **Current password** field is empty or contains **incorrect password**(!) at all!
3. enjoy having no password

**Expected Behavior**

**Save** should work only if **Current password** contains a valid current password!

**Logs**

**Screenshots**

Here i set new password and then click **Save** with empty **Current password** field:
https://user-images.githubusercontent.com/15073200/216780279-33594258-0b82-452e-9693-7a897c004d22.mp4

**System (please complete the following information):**
 - Platform: linux
 - Browser: brave
 - Jellyfin Version: 10.8.8 docker

**Additional Context**

**Comment by thornbill** [comment] 2023-02-08 23:48
Duplicate of https://github.com/jellyfin/jellyfin/issues/9208

**Closed** 2023-02-08 23:48 UTC
Labels: bug
