### ISSUE TITLE
Cast & Crew listing on Episode page does not include Guest Stars

### ISSUE THREAD

**Issue by bugfixin** [jellyfin/jellyfin-web#4352] opened 2023-02-13 08:09 UTC
When viewing the details of an episode, the Cast & Crew listing doesn't include people of type "guest star". I believe it should - there may be other categories of People that it should include and doesn't.

**Comment by bugfixin** [comment] 2023-02-16 19:08
I believe this stems from the filtering of the cast/crew to type "actor":

https://github.com/jellyfin/jellyfin-web/blob/master/src/controllers/itemDetails/index.js#L1846 

Seeing as the category is called "Cast & Crew" and not just "Cast" - why filter to actors-only? This behavior is notably different from the android TV app, which does display crew as well as actors.

**Comment by thornbill** [comment] 2023-06-14 03:05
Looks like a duplicate of #4148

**Closed** 2023-06-14 03:05 UTC
Labels: bug, duplicate
