### ISSUE TITLE
Movie filter:  HD and 4K return the same list

### ISSUE THREAD

**Issue by kamanwu** [jellyfin/jellyfin-web#3785] opened 2022-08-01 11:06 UTC
**Describe The Bug**
HD and 4K return the same list

**Steps To Reproduce**
Go to movie list, 
click "Filter" icon, 
click "Video Types". 
Choose "HD" to get the list.
Then switch to "4K" to get a new list.   
These 2 list are same,

**Expected Behavior**
HD filter only get HD movies
4K filter only list 4K movies

**Logs**
N/A

**Screenshots**
N/A

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.8.1

**Additional Context**
I am not sure it is jellyfin-web bug, or jellyfin server bug.

**Comment by kamanwu** [comment] 2022-08-05 12:04
10.8.3 has the same issue.

**Comment by Shadowghost** [comment] 2022-12-04 11:50
I still can't replicate this. The filter works as intended for me, all items with no 4k versions aren't show.

**Comment by thornbill** [comment] 2022-12-13 16:43
I also have not been able to replicate this in any recent version, so I'm going to close this. Please open a new issue with reproduction steps if this issue still affects you.

**Closed by thornbill** 2022-12-13 16:43 UTC
Labels: bug
