### ISSUE TITLE
Homepage inaccessible through localhost if not connected to the internet/offline

### ISSUE THREAD

**Issue by theguymadmax** [jellyfin/jellyfin-web#5772] opened 2024-07-11 19:15 UTC
**Describe The Bug**
If the server does not have a connection to the internet, then accessing the webui through 127.0.0.1:8096 causes the home page not to load. You'll get a blue spinning circle. 

Navigation to libraries is possible through direct URLs and playback of files is possible

Screenshots available on forum [post](https://forum.jellyfin.org/t-jellyfin-localhost-won-t-load-home-screen-library-categories-if-offline?).  

**Steps To Reproduce**
1. Disable ethernet or wifi on the local server
2. Start up server
3. On the localhost browse to 127.0.01:8096
4. After login observe that the home page doesn’t load, it hangs with a blue spinning circle.

**Logs**

[oflline.txt](https://github.com/user-attachments/files/16182499/oflline.txt)

**Screenshots**

**System (please complete the following information):**
 - Platform: Windows 11 2H32, Ubuntu 24.04
 - Browser: Firefox
 - Jellyfin Version: 10.9.7

**Additional Context**

Will work if you use an old 10.8.z webui build with the 10.9.z server branch. For example, JMP (web client 10.8.10 ) works without issue.

**Comment by thornbill** [comment] 2024-07-11 21:52
Duplicate of https://github.com/jellyfin/jellyfin/issues/12127

**Closed** 2024-07-11 21:52 UTC
Labels: bug, duplicate
