### ISSUE TITLE
'Preferred audio language' doesn't save 'Spanish;Castilian'

### ISSUE THREAD

**Issue by simonbcn** [jellyfin/jellyfin-web#824] opened 2020-02-18 10:02 UTC
- Arch Linux
- Firefox 73.0 / Chromium 80.0.3987.106
- Jellyfin 10.5.0 (_installed from jellyfin-git AUR package_)

Go to `Settings` > `Playback`, select `Spanish;Castilian`  in `Preferred audio language:` option. 
You leave this screen and re-enter and the selected language is `Spanish;Latin`.

**Logs**
https://pastebin.com/D7XYkFQh

**Comment by JustAMan** [comment] 2020-02-18 14:46
Duplicate of https://github.com/jellyfin/jellyfin/issues/1358 ?

**Comment by simonbcn** [comment] 2020-02-18 14:52
Yes, but that error was reported on May 7, 2019, is it still unresolved!!? :open_mouth:

**Comment by JustAMan** [comment] 2020-02-18 14:53
If it's open then it isn't fixed. Remember we're all volunteers here, which means nobody volunteered to fix that issue yet.

**Closed** 2020-02-18 14:53 UTC
Labels: bug, duplicate
