### ISSUE TITLE
Posters in my media with Chinese names are displayed as squares

### ISSUE THREAD

**Issue by Simba98** [jellyfin/jellyfin-web#2890] opened 2021-08-26 12:30 UTC
**Describe The Bug**

Posters in my media with Chinese names are displayed as squares. If I name some collections include Chinese names, they will be displayed as squares.

**Steps To Reproduce**

1. Name a collection with Chinese (Perhaps similar issue in JCK Characters)
2. Go to Home page
3. You will find that the Chinese in posters are squares.

**Expected Behavior**

Display JCK correctly.

**Logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/7941967/130962456-5c00e0c3-08f1-480c-9dba-02c3e8fa7cdb.png)

**System (please complete the following information):**
 - Platform:  I tested windows client (Jellyfin Media player), Android Client, and Web Site. All are same, and the posters are pictures, so I guess it is server issue.
 - Server Platform: Version: 10.7.6 Operating System: Linux Architecture: X64
 - Browser: Chrome and Edge Chrominum
 - Jellyfin Version: 10.7.6 

**Additional Context**

I enabled Settings -> Playback -> Fallback font folder path for fix ASS subtitle issue.
See #934 .

**Comment by Simba98** [comment] 2022-03-01 02:43
No repaired.

**Comment by thornbill** [comment] 2022-03-10 13:28
Duplicate of this server issue: https://github.com/jellyfin/jellyfin/issues/5008

**Closed by thornbill** 2022-03-10 13:28 UTC
Labels: bug
