### ISSUE TITLE
Poster not showing

### ISSUE THREAD

**Issue by spirillen** [jellyfin/jellyfin-web#2607] opened 2021-04-21 18:10 UTC
**Describe The Bug**
See screenshot, it kind a says everything....

**Steps To Reproduce**

1. Go to any content details
2. Click on any movie, music etc.
3. See error (screenshots)

**Expected Behavior**
The poster what be shown in a viewable way.

**Logs**
See https://github.com/jellyfin/jellyfin-web/issues/2606

**Screenshots**
![image](https://user-images.githubusercontent.com/44526987/115600575-26f51480-a2dd-11eb-90d4-b9daf8f3abd7.png)

![image](https://user-images.githubusercontent.com/44526987/115600529-18a6f880-a2dd-11eb-9cc2-fb39f9b679b8.png)

**System (please complete the following information):**
 - Platform: Ubunt 20.04.1 X64 (5.4.0-72-generic)
 - Browser: Firefox, Palemoon
 - Jellyfin Version: 10.7.2

**Additional Context**
This started to happen on latest updated version 

```shell
/usr/bin/jellyfin --version
Jellyfin.Server 10.7.2.0
```

**Comment by Stampede10343** [comment] 2021-04-21 18:33
I was just about to report this, I believe I figured out why it's not liking the image, but I'd have to investigate to figure out where its getting the decimal from.
This link returns a 400: `/Items/3e49fe312431cd19f332745ec5a2e933/Images/Primary?fillHeight=633&fillWidth=421.75&tag=37336dbffac293841989652e1d24811d&quality=90`
This one 200: `/Items/3e49fe312431cd19f332745ec5a2e933/Images/Primary?fillHeight=633&fillWidth=421&tag=37336dbffac293841989652e1d24811d&quality=90`

**Comment by cvium** [comment] 2021-04-21 18:41
Duplicate of #2587.

**Closed** 2021-04-21 18:42 UTC
Labels: bug

**Comment by spirillen** [comment] 2021-04-21 22:08
Hi @cvium Even if this should be a duplicate of #2587 and https://github.com/jellyfin/jellyfin/issues/5788 then there are both closed, without any reference to any fix, It seems mostly like you are just closing the issues, without doing something about it.

Is there actually a fix for this? is there any PR's solving this issue? I feeling this issue is left in the open to not being solved. Please enlighten me.

**Comment by cvium** [comment] 2021-04-22 05:39
> without any reference to any fix

![image](https://user-images.githubusercontent.com/675118/115661341-98fd4600-a33d-11eb-961a-ce972d4ecfab.png)

https://github.com/jellyfin/jellyfin-web/pull/2593

> It seems mostly like you are just closing the issues, without doing something about it.

I'm sorry you think that. Did you read the latest changelogs? https://github.com/jellyfin/jellyfin/releases

**Comment by Stampede10343** [comment] 2021-04-22 13:25
It is a bit unclear if you're not as familiar with some of the setup, but my understanding is that the issue was fixed in the API client, but that hasn't been pulled into the latest web build just yet, so it is fixed, but not currently in the latest release until they release again.
