### ISSUE TITLE
Direct playback screen flickers and trembles

### ISSUE THREAD

**Issue by Ainto** [jellyfin/jellyfin-web#3074] opened 2021-10-16 03:59 UTC
**Media Info of the file**
Basically all videos that can be played directly without transcoding.
(what I use here is mkv avc aac)

**Logs**
[2021-10-16 11:32:07.529 +08:00] [INF] [25] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "/media/1080p.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True

**FFmpeg Logs**
when I play, only the log ↑↑↑

**Stats for Nerds Screenshots**
![Screenshot](https://user-images.githubusercontent.com/21118134/137572847-31086af0-0d5b-4020-8cb7-cd995ef51a68.gif)

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: 10.7.7
 - Reverse proxy: No
 
**Client System (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Client: Web/Browser,
 - Browser (if Web client): Microsoft Edge
 - Client and Browser Version: 94.0.992.47 x64

When playing a video that supports direct playback, it will vibrate, and the transcoding playback will not basically. If the video is vibrated and then selected to transcode to other code rates, it will still vibrate.

**Comment by nyanmisaka** [comment] 2021-10-17 16:05
The HEVC plugin in MS store is broken for nearly a year.
Downgrade the plugin or disabled HWA in Edge.

Duplicate of https://github.com/jellyfin/jellyfin-web/issues/2180

**Comment by thornbill** [comment] 2021-10-18 02:23
Closing as duplicate.

**Closed** 2021-10-18 02:23 UTC
Labels: duplicate
