### ISSUE TITLE
.emby-scrollbuttons-button .paper-icon-button-light .i.md-icon

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin-web#486] opened 2019-09-29 10:31 UTC
**Describe the bug**
.emby-scrollbuttons-button .paper-icon-button-light .i.md-icon intermittently don't show, but only for some rows.

**Comment by dkanada** [comment] 2019-10-02 16:36
duplicate of #483

**Closed by dkanada** 2019-10-02 16:36 UTC
Labels: bug
