### ISSUE TITLE
Button icons aren't rendering in Firefox 72.0.1

### ISSUE THREAD

**Issue by dessalines** [jellyfin/jellyfin-web#700] opened 2020-01-15 18:20 UTC
On my local jellyfin installation, none of the button icons are rendering since I updated Firefox to `72.0.1`

![](https://i.imgur.com/2paWqcP.png)

```
Version: 10.4.3
Operating System: Linux
Architecture: X64
```

**Comment by dkanada** [comment] 2020-01-16 02:37
closing as duplicate of #693

**Comment by dkanada** [comment] 2020-01-16 02:38
We're working on it, hopefully the changes will be in the next release.

**Closed by dkanada** 2020-01-16 02:37 UTC
