### ISSUE TITLE
Android app v0.9.8 media resume not working with transcoding

### ISSUE THREAD

**Issue by 4luk** [jellyfin/jellyfin-web#815] opened 2020-02-16 01:38 UTC
Just updated to the latest Android mobile version 0.9.8 and now any time I transcode a movie it will start from the start. With no transcoding the movie will resume as normal.
Uninstall and reinstalled didn't help
Android tv works fine

**Comment by JustAMan** [comment] 2020-02-17 16:52
@dkanada this feels specific to Android, not jf-web, any reasons you moved it here?

**Comment by Artiume** [comment] 2020-02-18 02:41
I just attempted to replicate the issue on my android. I did not have issues so either the fix is in nightly or in my PR. I can try vanilla nightly to see if it's my PR

**Comment by Artiume** [comment] 2020-02-18 03:14
So I was unable to produce the issue using a nightly server.

**Comment by dkanada** [comment] 2020-02-18 05:15
I've seen this with a nightly server and the latest Android client, but the resume code isn't handled by Android so I doubt the issue is in that repository.

**Comment by Artiume** [comment] 2020-02-18 12:25
@dkanada i tried it with a vanilla nightly and it seemed fixed.

**Comment by dkanada** [comment] 2020-02-18 15:47
@Artiume can you give it a try once the new Android build gets pushed to GitHub? If resume and subtitles are both working we will release it on Google Play. Can you think of any other regressions mentioned in the last few days?

**Comment by Artiume** [comment] 2020-02-18 15:52
Hevc playback is broken but I think that issue was already present

**Closed** 2020-04-07 21:46 UTC
