### ISSUE TITLE
Images Won't Load

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin-web#3542] opened 2022-04-02 18:37 UTC
**Describe The Bug**
Images don't load

**Screenshots**
<img width="1252" alt="Screen Shot 2022-04-02 at 2 34 43 PM" src="https://user-images.githubusercontent.com/1161544/161396713-7e17674c-faee-44c8-b513-8d436bde1787.png">
<img width="1259" alt="Screen Shot 2022-04-02 at 3 02 41 PM" src="https://user-images.githubusercontent.com/1161544/161397611-2280d292-4c84-4adb-8fe6-f417e0dbd282.png">

**System (please complete the following information):**
 - Platform: Mac
 - Browser: All
 - Jellyfin Version: 10.7.x - 10.8.x

**Comment by phaelax** [comment] 2022-04-19 19:28
I get the same issue on Windows. What has fixed it for me was restarting the service. Are the images hosted locally or elsewhere on the network?

**Comment by phaelax** [comment] 2022-08-24 16:17
Currently running 10.8.3 and the issue hasn't reappeared for 99.9% of the time. I've had only one instance when scrolling through movies where a single row didn't appear. Scrolling that row offscreen and back on brought up the images.  I managed to repeat this once by scrolling very quickly. This was in Chrome 103.0.5060.134, couldn't reproduce in FF.

**Comment by jedthe3rd** [comment] 2023-01-08 22:43
I don't think #4069 fully fixed this issue. I am getting thumbnails sometimes loading, then unloading when I scroll away, then when I scroll back some of them load some of them don't.

![image](https://user-images.githubusercontent.com/7817335/211222602-291c2eda-5063-4b37-bf33-74d6af885efa.png)

The behavior is the same if I disable my custom CSS. 

This is on chrome Version 108.0.5359.125 (Official Build) (64-bit)

Firefox doesn't have this issue and edge doesn't seem to have this issue either.

**Comment by jedthe3rd** [comment] 2023-01-09 08:07
> I don't think #4069 fully fixed this issue. I am getting thumbnails sometimes loading, then unloading when I scroll away, then when I scroll back some of them load some of them don't.
> 
> ![image](https://user-images.githubusercontent.com/7817335/211222602-291c2eda-5063-4b37-bf33-74d6af885efa.png)
> 
> The behavior is the same if I disable my custom CSS.
> 
> This is on chrome Version 108.0.5359.125 (Official Build) (64-bit) I am on Jellyfin 10.8.8.
> 
> Firefox doesn't have this issue and edge doesn't seem to have this issue either.

Ignore this! I had an extension (Dark Reader) that was causing the issue.

**Comment by dmitrylyzo** [comment] 2023-01-09 19:22
Fixed by #4069

**Closed by dmitrylyzo** 2023-01-09 19:22 UTC
Labels: bug

**Comment by peterzolczer** [comment] 2023-09-14 08:44
I have this very issue on my fresh install on docker, 10.8.10. Blurry or no (cover/artist/poster/etc.) images, doesn't matter whether I use a client or open it in browser:

![image](https://github.com/jellyfin/jellyfin-web/assets/121183484/52c51393-fbd8-4ad3-b974-6e1ff04700a5)

**Comment by nielsvanvelzen** [comment] 2023-09-14 09:19
@peterzolczer please stop posting the exact same comment on multiple issues/pull requests. Especially the ones that were closed months ago.

**Comment by peterzolczer** [comment] 2023-09-14 09:21
Sorry about posting to multiple issues, since all of them are basically about the same issue, I didn't know which one to post to. Also, even though most of them are closed, the issue seems to be still active. Should I remove my comments from under the other issues?
