### ISSUE TITLE
Unable to play specific files with H.265 hard decoding enabled in Firefox

### ISSUE THREAD

**Issue by HMSRenown** [jellyfin/jellyfin-web#5728] opened 2024-06-24 16:27 UTC
**Describe The Bug**
When I enable Firefox's H.265 hardware support via the `media.wmf.hevc.enabled` pref in `about:config`
HEVC Video files don't play in Firefox. It endlessly spins like issue #5337 .
The encoded video file has been successfully transferred to the Jellyfin-Web, because my IDM extension successfully captured the entire episode of files.
Although [https://caniuse.com/hevc](url) shows that 10-bit or higher colors are not supported in Firefox, but I still could playback some other 10-bit H.265 video normally.

**Media Information**
Episode S01E20
Container: mp4
Path: C:\ProgramData\Jellyfin\Media\Shows\大明王朝1566 (2007) [tmdbid-68034]\Season 01\Episode S01E20.mp4
Size: 810 MB

Video
Title: 1080p HEVC SDR
Codec: HEVC
Codec tag: hev1
AVC: No
Profile: Main 10
Level: 120
Resolution: 1920x1044
Aspect ratio: 1.85:1
Anamorphic: No
Interlaced: No
Framerate: 25
Bitrate: 2259 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: AAC - Stereo - Default
Language: und
Codec: AAC
Codec tag: mp4a
AVC: No
Profile: LC
Layout: stereo
Channels: 2 ch
Bitrate: 128 kbps
Sample rate: 44100 Hz
Default: Yes
Forced: No
External: No

Video
Title: 720p PNG SDR
Codec: PNG
AVC: No
Resolution: 328x600
Anamorphic: No
Interlaced: No
Framerate: 90000
Bitrate: 2395 kbps
Video range: SDR
Video range type: SDR
Pixel format: rgb24
Ref frames: 1

**Screenshots**
![图片](https://github.com/jellyfin/jellyfin-web/assets/58620808/da796246-b908-4426-96b0-53cde49dd005)

**System (please complete the following information):**
 - Platform: Windows 2021 LTSC
 - Browser: Firefox 127.0.1
 - Jellyfin Version: 10.9.6

**Comment by polyzen** [comment] 2024-07-08 00:53
Seems to be a duplicate of #5706

**Closed** 2024-07-12 21:15 UTC
Labels: playback
