### ISSUE TITLE
Refreshing the page when watching a video results in a white page

### ISSUE THREAD

**Issue by almayor** [jellyfin/jellyfin-web#4100] opened 2022-10-25 14:14 UTC
**Describe The Bug**

Refreshing a page while a video is playing results in the homepage incorrectly rendered with a white background and missing fonts (see screenshot below).

**Steps To Reproduce**

1. Start playing a video
2. Refresh the webpage
3. Get redirected to homepage with missing fonts

If I refresh the page once more at this stage, all gets back to normal. 

**Expected Behavior**

A homepage that's shown correctly.

**Screenshots**

![271cb114-39d8-47ed-ba9b-9da7eb4f4f8a](https://user-images.githubusercontent.com/17319133/197797575-afffb9f4-74c8-4d9a-97ca-4e93b317f06c.png)

**System (please complete the following information):**
 - Platform: jellyfin/jellyfin Docker container running on macOS host as the server, macOS as the client
 - Browser: Chrome and Safari
 - Jellyfin Version: 10.8.5

**Additional Context**
I usually run the server behind a Nginx Proxy Manager in a Docker container and Cloudflare. Disabling Cloudflare did not solve the issue.

**Comment by thornbill** [comment] 2022-10-25 18:29
Duplicate of #559

**Closed by thornbill** 2022-10-25 18:29 UTC
Labels: bug
