### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'play' of object '#<HTMLMediaElement>'

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin-web#3524] opened 2022-03-28 22:50 UTC
**Describe The Bug**
Trying to get the index page from 10.8.0-beta1 fails.

**Steps To Reproduce**

1. Install 10.8.0-beta1 on Fedora 35
2. Navigate to the main page
3. See black screen
4. Observe error in Logs below in the Chrome devtools console

**Expected Behavior**
Should open up library

**Logs**
```
Uncaught TypeError: Cannot assign to read only property 'play' of object '#<HTMLMediaElement>'
    at main.jellyfin.bundle…23ea578dfc:2:320087
    at Object.45441 (main.jellyfin.bundle…23ea578dfc:2:320237)
    at i (main.jellyfin.bundle…3ea578dfc:2:1186901)
    at main.jellyfin.bundle…3ea578dfc:2:1232060
    at main.jellyfin.bundle…3ea578dfc:2:1254885
    at main.jellyfin.bundle…3ea578dfc:2:1254888
```

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Chrome
 - Jellyfin Version: 10.8.0-beta1

**Comment by dmitrylyzo** [comment] 2022-03-28 23:40
Chromium 99.0.4844.84 no error :man_shrugging: 

[This](https://github.com/jellyfin/jellyfin-web/blob/53ab8522528fe310a7270dd152d944bb577c471d/src/legacy/htmlMediaElement.js#L13-L25) can be `try/catch`ed, but if `play` doesn't return `Promise` then playback will fail.

The last thing we can do is wrap `elem.play()` calls (there is 2 currently) with some function that checks the return result.

**Comment by dmitrylyzo** [comment] 2022-03-30 09:06
I've installed Fedora 35 VM and Chromium Version 99.0.4844.51 (Official Build) Fedora Project (64-bit) - can't reproduce this issue.

**Comment by brianjmurrell** [comment] 2022-03-30 11:15
I'm using Chrome, not Chromium.

So what's the path forward on this?

**Comment by brianjmurrell** [comment] 2022-03-30 12:28
This browser installation works fine with 10.7.6 though.  So some difference in 10.8.0-beta1 seems to be the problem.

**Comment by brianjmurrell** [comment] 2022-03-30 13:22
> UPD: [Here](https://github.com/dmitrylyzo/jellyfin-web/commit/176fd6804472c812d37ce6c8cbe408815a73d129) is a possible fix that polyfills `play` only when necessary.

No luck.  Still getting:

```
Uncaught TypeError: Cannot assign to read only property 'play' of object '#<HTMLMediaElement>'
    at main.jellyfin.bundle…cdfaa61402:2:320445
    at Object.45441 (main.jellyfin.bundle…cdfaa61402:2:320547)
    at i (main.jellyfin.bundle…dfaa61402:2:1187211)
    at main.jellyfin.bundle…dfaa61402:2:1232370
    at main.jellyfin.bundle…dfaa61402:2:1255195
    at main.jellyfin.bundle…dfaa61402:2:1255198
```

**Comment by dmitrylyzo** [comment] 2022-03-30 13:27
> This browser installation works fine with 10.7.6 though. So some difference in 10.8.0-beta1 seems to be the problem.

Your browser is complaining about [this](https://github.com/jellyfin/jellyfin-web/blob/270430f6a110a97de3f1ea7edc4210ae41394ba7/src/legacy/htmlMediaElement.js) code, which was added in 10.8.

The idea is to make the `play` function return `Promise` (by standard) so that we don't need to check this everywhere.
Chrome 50+ doesn't require this polyfill because it complies that standard.

> No luck. Still getting:

:confused: It shouldn't reach [this block](https://github.com/dmitrylyzo/jellyfin-web/blob/176fd6804472c812d37ce6c8cbe408815a73d129/src/legacy/htmlMediaElement.js#L36-L46).

Could you tell me the exact version of your browser?

**Comment by brianjmurrell** [comment] 2022-03-30 15:11
99.0.4844.51 (Official Build) (64-bit)

I think 100.* just installed in the last 24h.  I can restart with it.  I need to restart in any case.

**Comment by brianjmurrell** [comment] 2022-04-01 20:32
Any progress we can make here?  I'd sure hate 10.8.0 to be final and it not even have the faintest of functionality here.  :-(

**Comment by dmitrylyzo** [comment] 2022-04-01 21:58
Any Chrome extension?

**Comment by brianjmurrell** [comment] 2022-04-01 22:52
Yes.  And if I try to open Jellyfin in an incognito window, it works!

But a regular window with all extensions works on 10.7.6.

I can try going through disabling some extensions and see if I can pinpoint the one.  If it is an extension.

**Comment by brianjmurrell** [comment] 2022-04-01 22:59
Haha.  That didn't take long.  I disabled https://chrome.google.com/webstore/detail/disable-html5-autoplay/efdhoaajjjgckpbkoglidkeendpkolai (I do notice that it is no longer maintained, which is a pity since those assholes at Google have caved to the advertisers and no longer allow disabling auto-play -- eating away at my very costly data) and then JF worked.  But I re-enabled it and it still works.  Strange.

**Comment by nielsvanvelzen** [comment] 2022-04-02 08:24
Closing this issue now since we can't do much about browser extension behavior, and the issue seems to be fixed.

**Closed by nielsvanvelzen** 2022-04-02 08:24 UTC
Labels: bug

**Comment by dmitrylyzo** [comment] 2022-04-03 21:49
@brianjmurrell It can be disabled per host.

In case anyone is wondering:
```js
Object.defineProperty(HTMLMediaElement.prototype, "play", {
    writable: false,
    configurable: false,
    enumerable: true,
    value: function() {
        // ...
    }
});
```

In addition, this can cause SyncPlay to have problems detecting playback permissions:
https://github.com/jellyfin/jellyfin-web/blob/891c63a3da93e802f9525aeb73c4de2f36175d1c/src/components/syncPlay/ui/playbackPermissionManager.js#L44
