### ISSUE TITLE
Every search result for content is limited to 24 items or less

### ISSUE THREAD

**Issue by Steve0w3n** [jellyfin/jellyfin-web#2089] opened 2020-11-20 08:56 UTC
I have only just recently started using jellyfin, I have multiple files with the same string(name) in the file name when I search for the string in the text box on jellyfin every result comes back with 24 items or less (I have way way more then 24 files with the string I'm searching for in the file name) This is extremely frustrating as I am having to go back threw my library of 9000+ videos manually just to find content with a specific string to add it to a collection.

I've noticed someone else has the issue here https://github.com/jellyfin/jellyfin-web/issues/1752
And someone suggested changing a line of javascript: query.Limit = enableScrollX() ? 24 : 16;  Changing the 24+ should allow more items to show? Is it possible in future releases to just make it query every file with a specific string by default?

If not I should be able to edit it my self server side.

**Comment by Steve0w3n** [comment] 2020-11-21 10:19
Seriously no one... I seriously thought i'd expect more from this shitty piece of software, Next time someone decides to write a fucking knock off version of plex at least write it so it is fucking stable.
At least plex matches my content and doesnt fucking randomly crash when scanning.... Ohhh and guess what what IT FUCKING SEARCHES FOR CONTENT CORRECTLY.

Rant over.

**Comment by oddstr13** [comment] 2020-11-21 12:45
Duplicate of #1752

**Closed by oddstr13** 2020-11-21 12:45 UTC
Labels: bug

**Comment by Steve0w3n** [comment] 2020-11-21 13:24
Starts shit talking on jellyfin, Closes bug report...

I could make a f dog with separation anxiety more stable then this piece of shit, Jellyfin is just a cruddy/knock off version of the emby source code. At least plex works.........

**Comment by YouKnowBlom** [comment] 2020-11-21 13:29
Closing duplicate issues is usually what happens as they add extra noise to an otherwise already busy issue tracker

**Comment by Steve0w3n** [comment] 2020-11-21 13:42
Maybe the people that write jellyfin should spend less time closing/not replying to urgent requests and more time writing some code that will fucking work. Excuse my language but this is by far the fucking worse media server I have ever used. I may come back to it if(That is a big IF) they make it more stable, But jesus christ even my dog with separation anxiety is more stable then this. Like have they never heard of a regex?
https://stackoverflow.com/questions/185378/regular-expression-to-match-start-of-filename-and-filename-extension

**Comment by oddstr13** [comment] 2020-11-21 14:02
My condolences on your bad day.

Now, if you will excuse me, I'll go back to [fixing plugins for the upcoming release](https://github.com/jellyfin/jellyfin-plugin-playbackreporting/pull/26/commits).
