### ISSUE TITLE
Pushing Enter key when editing metadata in web interface closes window without saving

### ISSUE THREAD

**Issue by tamburra** [jellyfin/jellyfin-web#2184] opened 2020-12-05 15:06 UTC
**Describe the bug**
When editing metadata from the web interface, pushing the enter key closes the popup window without saving.  When pushing enter in textarea fields such as OVERVIEW you get a new line. But if the cursor is on a single text field the enter key just closes the window. The enter key also closes the window even if the cursor is not set on any field.  I have made this mistake numerous times when editing metadata and lose everything i was editing at the time.

Not sure if this is a bug or a feature but it would be nice if the enter key did nothing instead of closing the window without saving when the cursor is placed in a single text field.

**System (please complete the following information):**
Jellyfin 10.6.4

**To Reproduce**
1. Go to edit metadata on a tv show or movie
2. Place cursor on the title field and type something
3. Push enter on the keyboard.
4. Watch as everything goes bye-bye

**Expected behavior**
Enter key should at least save the info.

**Comment by MrTimscampi** [comment] 2020-12-05 17:09
The enter key submits the form, which is generally expected behavior.

So your data doesn't go bye-bye, it gets sent to the server and applied to the item you were editing.

**Comment by thornbill** [comment] 2020-12-05 17:35
I agree. This seems to be the general way forms behave on the web. Tab should switch between fields and enter submits the form.

**Comment by tamburra** [comment] 2020-12-06 08:17
My issue is stating that it is NOT saving when you press enter. Please read my issue again.

**Comment by thornbill** [comment] 2020-12-17 20:32
I haven't been able to replicate this. It seems to save for me whenever I hit enter in Firefox and Chrome. I did notice that sometimes I have to refresh the page to see the updated information though.

Is there any additional information you can provide on how to reproduce the issue? Thanks!

**Comment by fffrankieh** [comment] 2021-01-30 13:29
This is the problem I fixed in #1948, but there haven't been any stable releases since that was merged.

**Comment by thornbill** [comment] 2021-01-30 23:02
Ok great! I tagged it to be included in the next 10.7 RC.

**Closed by thornbill** 2021-01-30 23:02 UTC
Labels: bug, question
