### ISSUE TITLE
[BUG]: Play music -> Log out -> music ... continues. :D

### ISSUE THREAD

**Issue by systemcrash** [jellyfin/jellyfin-web#5435] opened 2024-04-30 16:12 UTC
**Describe The Bug**
Play music -> Log out -> music ... continues. :D

**Steps To Reproduce**
Play music -> Log out 

**Expected Behavior**
Play music -> Log out -> music ... stops. :D

**Logs**

**Screenshots**

![Screenshot 2024-04-30 at 18 04 08](https://github.com/jellyfin/jellyfin-web/assets/647633/577ac230-5da9-4ea2-a7d7-147cbb6ca67a)

![IMG_0919](https://github.com/jellyfin/jellyfin-web/assets/647633/1f247953-5237-4b6a-9dab-011742e47fae)

**System (please complete the following information):**
Happens on mobile, desktop, all browsers....

Pretty sure this shouldn't happen. Pretty sure it happens with all media types if the logout button is visible/accessible.

**Comment by systemcrash** [comment] 2024-04-30 16:14
Server version
10.9.0
Web version
10.9.0
Build version
2024042905

**Comment by thornbill** [comment] 2024-04-30 23:51
Duplicate of #4917

**Closed** 2024-04-30 23:51 UTC
Labels: bug
