### ISSUE TITLE
[Issue]: song tag character escaping - ampersand (&) shows up as "&amp;" in playlist and car stereo screen

### ISSUE THREAD

**Issue by meonkeys** [jellyfin/jellyfin-web#4078] opened 2022-10-20 17:55 UTC
### Please describe your bug

Sometimes an ampersand (or other non low-ASCII character like a smart quote or em dash) shows up as the corresponding HTML entity. This happens in various places such as the expanded queue view in the web ui, the android client, and when a song is playing via bluetooth on my car stereo and the name is shown on a display. For the sake of this issue maybe we focus on the problem in the web ui, but I'm filing this issue in the "server" project assuming the issue actually originates at the server level. I may be wrong about this.

### Jellyfin Version

Other

### if other:

Server: d7745890f780  Version: 10.8.5

### Environment

I use [the container provided by linuxserver.io](https://hub.docker.com/r/linuxserver/jellyfin).

```markdown
- OS: Linux x86-64
- Virtualization: Docker container on a 64-bit Ubuntu 20.04 LTS host
- Clients: web and android client
- Browser: multiple
- FFmpeg Version: 5.1.2-Jellyfin
- Playback Method: direct
- Hardware Acceleration: n/a
- Plugins: AudioDB 10.8.5.0, Cover Art Archive 7.0.0.0, Fanart 10.0.0.0, MusicBrainz 10.8.5.0, OMDb 10.8.5.0, Playback Reporting 13.0.0.0, Reports 15.0.0.0, Studio Images 10.8.5.0, TMDb 10.8.5.0
- Reverse Proxy: Traefik
- Base URL: https://jellyfin.example.com/ - (root / no path)
- Networking: Docker
- Storage: local
```

### Please attach any screenshots here

![web](https://user-images.githubusercontent.com/50639/197022272-3ea45f0c-6bb3-4c61-abd6-c8a4478935d2.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AntiBlueQuirk** [comment] 2022-10-21 16:05
The issue for the Play Queue is caused by this code. The artist name gets escaped outside the string template as well as inside.

https://github.com/jellyfin/jellyfin-web/blob/f8b0c941f5e97d99cd27cf69e6fe3962314577d5/src/components/remotecontrol/remotecontrol.js#L148-L150

**Comment by crobibero** [comment] 2022-10-22 23:46
Fixed by https://github.com/jellyfin/jellyfin-web/pull/4089

**Closed by crobibero** 2022-10-22 23:46 UTC
Labels: bug
