### ISSUE TITLE
Jellyfin not using icon library, relying on system font.

### ISSUE THREAD

**Issue by dessalines** [jellyfin/jellyfin-web#972] opened 2020-03-09 17:00 UTC
I thought there was an issue for this, but I can't find one.

![](https://i.imgur.com/YmmXS1Y.png)

Jellyfin doesn't seem to work with different browser fonts. It should be using a cross-platform icon / svg library, maybe something like fork-awesome, or just import custom svgs.

**Comment by MrTimscampi** [comment] 2020-03-22 23:29
Which version of Jellyfin are you using ? Which browser and which operating system ?

**Comment by dessalines** [comment] 2020-03-23 01:38
- Jellyfin web 10.5.0
- FF 74
- Arch linux.

This is when I'm using a custom system font, which the icons in jellyfin shouldn't be relying on, it should be using a cross-platform icon library.

**Comment by MrTimscampi** [comment] 2020-03-23 06:40
Jellyfin isn't relying on any of your system fonts, as we ship Material Icons for our icons and Noto Sans for regular fonts.

I suspect your font redirection is too aggressive and overrides Material Icons.

A few of the icons are using ligatures, which is why they are not showing up. We have been moving to CSS classes instead, hence why the Play button is showing up.  
However, there's a lot of icons all over the UI and it will take some time.

In the short term, you can put an exception on Material Icons, depending on what you use for font replacement, or disable it when visiting your server.

The move to CSS classes is planned to be completed, but there's no ETA.

**Comment by frankyifei** [comment] 2020-03-25 20:43
check the box for allowing page to use their own fonts

**Comment by MrTimscampi** [comment] 2020-04-05 19:44
Closing this as it's essentially a duplicate of #855

**Closed by MrTimscampi** 2020-04-05 19:44 UTC

**Comment by pvanheus** [comment] 2020-05-04 12:08
In case someone else comes to this issue, I saw this behaviour when I had Jellyfin running behind a nginx reverse proxy but without SSL enabled. Enabling SSL fixed this for me.
