### ISSUE TITLE
We need directplay version of Jellyfin without transcoding bloatware

### ISSUE THREAD

**Issue by evrial** [jellyfin/jellyfin-web#4778] opened 2023-09-16 09:48 UTC
When running Jellyfin server from RPi 4 or any similar SBC you cannot turn off transcoding in any chanse. It in always ON even when disabled checkbox for video/audio in user profile. I want to get rid to that entirely and never look back, we live in 2023 when every device capable of HEVC also knows as H.265 HW decoding yet I cannot utilize than in Chrome web client with HW acceleration ON and AMD 5600X processor, this is a joke. I cannot utilize HW decoding on Pixel 6 Pro android client which support all HW decoding codecs known to human.

Versions: everything actual up to this date.

**Comment by evrial** [comment] 2023-09-16 15:51
Ok after spending some time I figured DTS and Dolby AC3 audio codecs are unsupported in Chrome, yet it struggled to even play damn video, that's pathetic
```
Sep 16 18:47:14 DietPi jellyfin[19312]: [18:47:14] [INF] User policy for jellyfin. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False
Sep 16 18:47:14 DietPi jellyfin[19312]: [18:47:14] [INF] StreamBuilder.BuildVideoItem( Profile=Anonymous Profile, Path=/mnt/ssd/dietpi_userdata/Фильмы/I.Am.Legend.2007.2in1.1080p.BluRay.DTS.x264-ESiR.mkv, AudioStreamIndex=1, SubtitleStreamIndex=-1 ) => ( PlayMethod=Transcode, TranscodeReason=VideoCodecNotSupported, AudioCodecNotSupported ) media:/videos/2819ff84-97c6-11ef-b615-d5f12d8ec3a3/master.m3u8?MediaSourceId=2819ff8497c611efb615d5f12d8ec3a3&VideoCodec=h264,h264&AudioCodec=aac,mp3&AudioStreamIndex=1&VideoBitrate=139616000&AudioBitrate=384000&MaxFramerate=23.976042&api_key=<token>&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=138f619c6157d3dfe442182ad49f8987&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-level=51&h264-videobitdepth=8&h264-profile=high&h264-rangetype=SDR&h264-deinterlace=true&TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported
```

**Comment by evrial** [comment] 2023-09-16 15:57
What can we do about DTS and AC3 audio?

**Comment by TimGels** [comment] 2023-09-16 16:34
![afbeelding](https://github.com/jellyfin/jellyfin-web/assets/43609220/4cdcfc9a-21dd-4c22-b581-ede20cd8244a)
These options don't work for you?

**Comment by sevenrats** [comment] 2023-09-16 16:57
We really don't recommend using a raspberry pi as a server for this exact reason.  Because of the complex interrelationship of different codecs and containers, it's nearly impossible to to playback on a variety of devices without transcoding. I recommend you obtain a more powerful server.

**Comment by evrial** [comment] 2023-09-16 16:57
Yea I can't transcode video from RPi 4 and Jellyfin asking for transcoding both video and audio
From the logs we can see TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported
Which is wrong, only audio (DTS) not supported and need transcoding, not stupid x264 video. And Android client plays DTS audio by transcoding which is turned off, what a mess. Overall experience with DTS and Dolby audio files is poor.

Sep 16 19:41:18 DietPi jellyfin[19312]: [19:41:18] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -ss 01:23:38.760 -fflags +genpts -f matroska,webm  -i file:"/mnt/ssd/dietpi_userdata/Фильмы/I.Am.Legend.2007.2in1.1080p.BluRay.DTS.x264-ESiR.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 836 -hls_segment_filename "/mnt/dietpi_userdata/jellyfin/transcodes/9b1a7ba3ee844d004e03ba05c1158c8a%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/mnt/dietpi_userdata/jellyfin/transcodes/9b1a7ba3ee844d004e03ba05c1158c8a.m3u8"
Sep 16 19:41:19 DietPi jellyfin[19312]: [19:41:19] [WRN] Slow HTTP Response from http://pi.hole:8097/videos/2819ff84-97c6-11ef-b615-d5f12d8ec3a3/hls1/main/836.ts?DeviceId=df0d0f4c2b28bda04f893981f7db47a9a49cb05546967d87&MediaSourceId=2819ff8497c611efb615d5f12d8ec3a3&VideoCodec=h264,h264&AudioCodec=aac,mp3&AudioStreamIndex=1&VideoBitrate=139616000&AudioBitrate=384000&MaxFramerate=23.976042&PlaySessionId=032afbd7075541dea46e6b70ad42f7e6&api_key=685133d752a3475db940c3596f179ce5&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=138f619c6157d3dfe442182ad49f8987&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&h264-level=41&h264-videobitdepth=8&h264-profile=high&TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported&runtimeTicks=50187600000&actualSegmentLengthTicks=42120000 to 192.168.3.185 in 0:00:00.5517743 with Status Code 200
Sep 16 19:41:39 DietPi jellyfin[19312]: [19:41:39] [WRN] Slow HTTP Response from http://pi.hole:8097/Sessions/Playing/Progress to 192.168.3.185 in 0:00:00.6736597 with Status Code 204

**Comment by sevenrats** [comment] 2023-09-16 17:02
I mean, its possible that its failing over instead of just failing to play back.  It's rarely as simple as "supporting a codec" codecs have different profiles, and different levels, and rarely does a particular piece of hardware support all of them.  Its entirely possible for a client to support HEVC, for example, but not HEVC MAIN10.
We would need to see the transcode log for this to be sure what it's doing. It's possible there is just a bug in the TranscodeReason.

**Comment by sevenrats** [comment] 2023-09-16 17:04
also, this kinda looks like your video file has a 139 megabyte per second bitrate?  So, there you go. That's likely well above the maximum supported bitrate.

**Comment by evrial** [comment] 2023-09-16 17:10
Here some info 
```
/usr/lib/jellyfin-ffmpeg/ffmpeg -i I.Am.Legend.2007.2in1.1080p.BluRay.DTS.x264-ESiR.mkv
ffmpeg version 5.1.3-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --toolchain=hardened --enable-cross-compile --arch=arm64 --cross-prefix=/usr/bin/aarch64-linux-gnu-
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, matroska,webm, from 'I.Am.Legend.2007.2in1.1080p.BluRay.DTS.x264-ESiR.mkv':
  Metadata:
    title           : I.Am.Legend.2007.2in1.1080p.BluRay.DTS.x264-ESiR
    encoder         : libebml v0.7.7 + libmatroska v0.8.1
    creation_time   : 2008-04-04T16:34:19.000000Z
  Duration: 01:56:58.36, start: 0.000000, bitrate: 12541 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 2104.400000
    Chapter #0:1: start 2123.229000, end 4384.086000
    Chapter #0:2: start 4452.540000, end 5334.100000
    Chapter #0:3: start 6234.236000, end 7018.163000
  Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x800, SAR 1:1 DAR 12:5, 23.98 fps, 23.98 tbr, 1k tbn (default)
  Stream #0:1(rus): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Metadata:
      title           : DD 5.1 @ 384kbps
  Stream #0:2(rus): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s
    Metadata:
      title           : DTS 5.1 @ 1.5 Mbit
  Stream #0:3(eng): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s
    Metadata:
      title           : DTS 5.1 @ 1.5 Mbit
  Stream #0:4(rus): Subtitle: ass (default)
    Metadata:
      title           : alternate episodes only
  Stream #0:5(eng): Subtitle: ass
  ```
Video plays smooth from RPi as locally from filebrowser html5 video in latest Chrome, only silent because DTS audio.

**Comment by oddstr13** [comment] 2023-09-16 17:14
I guess it is possible that admin users are able to bypass the transcoding permission?

I would recommend that you utilize a different client, one that can play back most (if not all) media without transcoding.
- https://github.com/jellyfin/jellyfin-media-player
- https://github.com/jellyfin/jellyfin-kodi

Are a couple of examples of this.

Another alternative is to more actively curate your media collection, and pre-transcode your media with HandBrake before adding to your media library.

**Comment by JPVenson** [comment] 2023-09-16 17:15
Your media is encoded in `h264 (High)` i know no hardware that supports this

**Comment by sevenrats** [comment] 2023-09-16 17:15
jellyfin doesn't use html5 for video playback so this is unrelated.  the core of your issue has to do with your own misunderstandings about how the system works and why.  i recommend getting a more powerful server, configuring hwa, and enabling transcoding.  This is how jellyfin is meant to be used.

**Comment by evrial** [comment] 2023-09-16 17:22
jellyfin uses web browser for video playback and HW decoding. You can play MKV file with HEVC and supported audio codec like AAC directly from Chrome. I made a test file to check that

```
<script type="text/javascript">
 function failed(e) {
   // video playback failed - show a message saying why
   switch (e.target.error.code) {
     case e.target.error.MEDIA_ERR_ABORTED:
       alert('You aborted the video playback.');
       break;
     case e.target.error.MEDIA_ERR_NETWORK:
       alert('A network error caused the video download to fail part-way.');
       break;
     case e.target.error.MEDIA_ERR_DECODE:
       alert('The video playback was aborted due to a corruption problem or because the video used features your browser did not support.');
       break;
     case e.target.error.MEDIA_ERR_SRC_NOT_SUPPORTED:
       alert('The video could not be loaded, either because the server or network failed or because the format is not supported.');
       break;
     default:
       alert('An unknown error occurred.');
       break;
   }
 }
</script>


<video src="I.Am.Legend.2007.2in1.1080p.BluRay.DTS.x264-ESiR.mkv" autoplay controls onerror="failed(event)" ></video>
```

**Comment by sevenrats** [comment] 2023-09-16 17:28
sure, an hevc file with supported profiles with a supported audio track will play fine. and this file will play fine in jellyfin too, probably.  But your 10 bit h264 High video track is not going to unless you transcode it. and nither is the dts audio.  Since there is a mismatch between your media types and the hardware you want to play it on, transcoding is going to be necessary.  Again, just ditch the pi.

**Comment by evrial** [comment] 2023-09-16 17:32
This video is playing smooth as butter in Windows jellyfin client without any transcoding, but web client is endless spinning wheel on top of thumbnail image.

**Comment by sevenrats** [comment] 2023-09-16 17:33
yes this is to be expected since your pi cannot transcode usefully.  jellyfin media player will not require transcoding as it will have support for these codecs. JMP uses MPV as its video player, plus there is lots of clever code inside it to maximize client hwa opportunities

**Comment by evrial** [comment] 2023-09-16 17:36
Totally makes sense, but at least video stream should be available with meaningfull error why client doesn't support such codecs for direct play.

**Comment by oddstr13** [comment] 2023-09-16 17:36
It does not help that the browser can play the file, if it does not disclose it to Jellyfin.
Detecting which codecs and codec parameters are supported by the browser is an incredibly complex task, as there are so many variations.
Even if the codec itself is supported, it may not be supported in all container formats, and the browser may not be properly reporting it via the JavaScript APIs.

Some information about browser support for video codecs in [Mozilla's documentation on media formats](https://developer.mozilla.org/en-US/docs/Web/Media/Formats#media_file_types_and_codecs)
[Can I use has a compatibility matrix](https://caniuse.com/?search=video%20format) for some formats

**Comment by sevenrats** [comment] 2023-09-16 17:37
> Totally makes sense, but at least video stream should be available with meaningfull error why client doesn't support such codecs for direct play.

you could open a feature request for this if you wanted. better error feedback seems like a reasonable ask. features.jellyfin.org

**Comment by evrial** [comment] 2023-09-16 17:49
https://cconcolato.github.io/media-mime-support/
From this page I see that AVC is green and DTS is red, AC-3 is also red, can we use that before streaming to inform the user?

**Comment by sevenrats** [comment] 2023-09-16 18:08
one of the team has confirmed that there is a bug in the transcode reasons that has already been fixed in master. https://github.com/jellyfin/jellyfin/pull/9051
this is why i asked for your transcode logs so we could see what it was actually doing.

**Comment by evrial** [comment] 2023-09-16 18:29
jellyfin --version
Jellyfin.Server 10.8.10.0
When streaming from web ffmpeg not invoked at all:
```
Sep 16 21:26:13 DietPi jellyfin[19312]: [21:26:13] [INF] User policy for jellyfin. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False
Sep 16 21:26:13 DietPi jellyfin[19312]: [21:26:13] [INF] StreamBuilder.BuildVideoItem( Profile=Anonymous Profile, Path=/mnt/ssd/dietpi_userdata/Фильмы/I.Am.Legend.2007.2in1.1080p.BluRay.DTS.x264-ESiR.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=VideoCodecNotSupported, AudioCodecNotSupported ) media:/videos/2819ff84-97c6-11ef-b615-d5f12d8ec3a3/master.m3u8?MediaSourceId=2819ff8497c611efb615d5f12d8ec3a3&VideoCodec=h264,h264&AudioCodec=aac,mp3&AudioStreamIndex=1&VideoBitrate=139616000&AudioBitrate=384000&MaxFramerate=23.976042&api_key=<token>&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=138f619c6157d3dfe442182ad49f8987&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-level=51&h264-videobitdepth=8&h264-profile=high&h264-rangetype=SDR&h264-deinterlace=true&TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported
```
When from Android client there is an audio and video playback and transcoding happening
```
Sep 16 21:24:05 DietPi jellyfin[19312]: [21:24:05] [INF] FFmpeg exited with code 0
Sep 16 21:24:05 DietPi jellyfin[19312]: [21:24:05] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -ss 00:14:55.602 -fflags +genpts -f matroska,webm  -i file:"/mnt/ssd/dietpi_userdata/Фильмы/I.Am.Legend.2007.2in1.1080p.BluRay.DTS.x264-ESiR.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 149 -hls_segment_filename "/mnt/dietpi_userdata/jellyfin/transcodes/feff015061471d6dde5ea94897c87b35%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/mnt/dietpi_userdata/jellyfin/transcodes/feff015061471d6dde5ea94897c87b35.m3u8"
```

**Comment by cvium** [comment] 2023-09-16 19:08
-codec:v:0 copy
-codec:a:0 copy

It is remuxing the streams into a different container. HLS in this instance.

**Comment by evrial** [comment] 2023-09-16 19:16
Yea, interesting why MKV container not supported
![Screenshot 2023-09-16 221432](https://github.com/jellyfin/jellyfin-web/assets/341680/87150f6a-13ef-4225-bef7-94f9677e6ea9)

**Comment by evrial** [comment] 2023-09-16 19:37
I actually turned on audio transcoding and ffmpeg process loads 1 of 4 cores to 99% but plays without stutter and RPi is very capable for audio.

**Comment by thornbill** [comment] 2023-09-16 19:46
There is no browser support for playing mkv files. _Sometime_ playing an mkv in a browser will work because browsers do support webm which is a subset of mkv. Any mkv file that uses features outside what webm supports would fail to play.

**Comment by evrial** [comment] 2023-09-16 19:56
I checked just for fun every MKV file I have in Chrome and all of them have video playback, when Chrome supports audio codec, even with audio. But MKV should be supported by Android client

**Comment by TimGels** [comment] 2023-09-16 23:00
> I actually turned on audio transcoding and ffmpeg process loads 1 of 4 cores to 99% but plays without stutter and RPi is very capable for audio. Without that setting media is not loading.

It goes to 99% because it tries to encode as fast as it can, faster than the video/ audio speed (when hardware is fast enough).

**Comment by evrial** [comment] 2023-09-17 06:39
I made a feature request, would like to see your comments
https://features.jellyfin.org/posts/2319/more-informative-of-client-codec-ability-for-direct-play-transcoding-function

**Comment by thornbill** [comment] 2023-09-21 16:24
Closing since this is now covered by a feature request.

**Closed** 2023-09-21 16:24 UTC
Labels: playback
